#!chezscheme
;; B' cleanup records -- execution cells (design v4 §6): executor death,
;; send-allocation failure, competing executors, competing ordinary completion,
;; hint loss. Plaintext node a, plain peer b (test/plain-peer.sc).
;;
;; Who executes a record: after a KILL the link reaper's DOWN handler runs
;; remove-peer! (one bounded round; the rest by its rescan); after a clean
;; peer close the LINK's own guard runs it (unbounded). The cells choose the
;; executor by choosing kill vs close.
(import (chezscheme) (igropyr actor) (igropyr node)
        (only (igropyr libuv) now-ms)
        (igropyr inject-control)
        (test plain-peer))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (within? ms thunk)
  (let ((deadline (+ (now-ms) ms)))
    (let loop () (cond ((thunk) #t) ((> (now-ms) deadline) #f) (else (sleep-ms 20) (loop))))))
(define port 18720)
(define secret "cleanup-record-exec-secret-0123456789abcdef")
(define BOOT-X "feedfacefeedface")
(define (stat key) (let ((p (assq key (node-monitor-stats)))) (and p (cdr p))))
(define (arm! point occ) (inject-arm-barrier! point occ 60000))
(define (wait! t point ms) (inject-barrier-wait t point ms))
(define (resume! t w) (when (pair? w) (send (cdr w) (vector 'inject-resume t))))
(define (cleanup! t point) (guard (e (#t (void))) (inject-release! t)) (guard (e (#t (void))) (inject-barrier-cleanup! t point 2000)))
(define (show w) (if (and (pair? w) (not (symbol? (cdr w)))) (list (car w) (process-id (cdr w))) w))
(define (open-b boot gen) (plain-peer-open "127.0.0.1" port "b" boot gen secret 6000))
(define (expect-up! label ms) (receive (after ms (check label #f 'no-node-up)) (`#(node-up b) (check label #t))))
(define (expect-down! label ms) (receive (after ms (check label #f 'no-node-down)) (`#(node-down b) (check label #t))))
(define (noconnection? r) (and (vector? r) (eq? (vector-ref r 0) 'rcall-error) (eq? (vector-ref r 1) 'noconnection)))
(define (timeout-error? r) (and (vector? r) (eq? (vector-ref r 0) 'rcall-error) (eq? (vector-ref r 1) 'timeout)))
;; n callers whose calls stay pending (the peer does not answer); each reports #(call-outcome i r)
(define (spawn-callers! n main tmo)
  (let loop ((i 0)) (when (< i n) (spawn (lambda () (send main (vector 'call-outcome i (guard (e (#t e)) (rcall 'b 'svc (list 'q i) tmo)))))) (loop (+ i 1)))))
;; collect outcomes for n callers within ms -> alist i -> r (each i at most once by construction)
(define (collect-calls n ms)
  (let ((deadline (+ (now-ms) ms)))
    (let loop ((acc '()))
      (if (or (= (length acc) n) (> (now-ms) deadline)) acc
          (receive (after (max 1 (- deadline (now-ms))) acc)
            (`#(call-outcome ,i ,r) (loop (cons (cons i r) acc))))))))
;; n remote monitors b/m0..m(n-1) -> mrefs; collect their remote-downs
(define (arm-monitors! n) (let loop ((i 0) (acc '())) (if (= i n) (reverse acc) (loop (+ i 1) (cons (monitor-remote 'b (string->symbol (string-append "m" (number->string i)))) acc)))))
(define (collect-downs n ms)
  (let ((deadline (+ (now-ms) ms)))
    (let loop ((acc '()))
      (if (or (= (length acc) n) (> (now-ms) deadline)) acc
          (receive (after (max 1 (- deadline (now-ms))) acc)
            (`#(remote-down b ,name ,reason) (loop (cons (cons name reason) acc))))))))
(define (all-noconnection? outcomes n) (and (= (length outcomes) n) (for-all (lambda (p) (noconnection? (cdr p))) outcomes)))
(define (all-down-once? downs n) (and (= (length downs) n) (for-all (lambda (p) (eq? (cdr p) 'noconnection)) downs)
                                      (let ((names (map car downs))) (= (length names) (length (let dedup ((l names) (seen '())) (cond ((null? l) seen) ((memq (car l) seen) (dedup (cdr l) seen)) (else (dedup (cdr l) (cons (car l) seen))))))))))
(define (no-stray-downs! label ms) (receive (after ms (check label #t)) (`#(remote-down b ,name ,reason) (check label #f (list name reason)))))
(define (reaper) (whereis 'igropyr-node-link-reaper))
(define (records-finished? ms) (within? ms (lambda () (eqv? (stat 'cleanup-records) 0))))

(start-scheduler
  (lambda ()
    (define main self)
    (register 'main self)
    (register 'svc (spawn (lambda () (let loop () (receive (x (loop)))))))   ; a hosted-monitor target on a
    (node-start! 'a secret port "127.0.0.1")
    (monitor-node 'b)
    (let ((rbase (stat 'rmonitors)) (obase (stat 'owner-agents)) (cbase (stat 'callee-agents)))

      ;; ---- N3: the executor (the reaper, after a kill) dies inside cleanup ----
      (for-each
        (lambda (spec)
          (let ((point (car spec)) (occ (cadr spec)) (label (caddr spec)))
            (let ((b1 (open-b BOOT-X 1)))
              (check (string-append label ": b installed") (not (pair? b1)) b1)
              (expect-up! (string-append label ": node-up b") 3000)
              (let* ((nmon (cadddr spec)) (mrefs (arm-monitors! nmon)))
                (spawn-callers! 3 main 30000)
                (check (string-append label ": the peer saw the frames") (and (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call))) 3000) #t))
                (let ((t (arm! point occ)) (r0 (reaper)))
                  (kill ($node-link-pid 'b) 'n3-kill)
                  (let ((w (wait! t point 8000)))
                    (check (string-append label ": the executor parked at " (symbol->string point)) (and (pair? w) (eq? (cdr w) r0)) (show w))
                    (when (pair? w)
                      (check (string-append label ": premise -- the record is pending") (eqv? (stat 'cleanup-records) 1) (stat 'cleanup-records))
                      (kill (cdr w) 'n3-executor-killed)
                      (guard (e (#t (void))) (inject-release! t))))
                  (cleanup! t point))
                ;; the warden restarts the reaper; its startup rescan finishes the record
                (check (string-append label ": a reaper is back") (within? 5000 (lambda () (let ((r (reaper))) (and r (process-alive? r))))))
                (expect-down! (string-append label ": node-down b") 8000)
                (let ((outs (collect-calls 3 10000)) (downs (collect-downs nmon 15000)))
                  (check (string-append label ": every pending call failed exactly once") (all-noconnection? outs 3) outs)
                  (check (string-append label ": every monitor fired DOWN exactly once") (all-down-once? downs nmon) (length downs)))
                (no-stray-downs! (string-append label ": no duplicate remote-down") 800)
                (check (string-append label ": the peer's socket was closed (close obligation done)") (within? 5000 (lambda () (plain-peer-closed? b1))))
                (check (string-append label ": the record finished") (records-finished? 8000) (stat 'cleanup-records))
                (check (string-append label ": owner agents back to base") (within? 5000 (lambda () (eqv? (stat 'owner-agents) obase))) (stat 'owner-agents) obase)
                (check (string-append label ": rmonitors back to base") (eqv? (stat 'rmonitors) rbase) (stat 'rmonitors) rbase))
              (plain-peer-close! b1)
              (sleep-ms 300))))
        '((cleanup-after-publish 1 "N3a" 5) (cleanup-before-round 2 "N3b" 70) (cleanup-before-control 1 "N3c" 5)))

      ;; ---- N4: competing executors (link guard vs the reaper's rescan) --------
      (let ((b1 (open-b BOOT-X 1)))
        (check "N4: b installed" (not (pair? b1)) b1)
        (expect-up! "N4: node-up b" 3000)
        (let ((mrefs (arm-monitors! 6)))
          (spawn-callers! 3 main 30000)
          (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call))) 3000)
          (let ((t (arm! 'cleanup-before-round 1)) (link ($node-link-pid 'b)))
            (plain-peer-close! b1)                         ; clean close: the LINK's guard is the primary
            (let ((w (wait! t 'cleanup-before-round 8000)))
              (check "N4: the primary (the link) parked before its first round" (and (pair? w) (eq? (cdr w) link)) (show w))
              (expect-down! "N4: node-down b (enqueued in the transaction)" 6000)
              ;; the reaper's periodic rescan runs the record to completion meanwhile
              (let ((outs (collect-calls 3 10000)) (downs (collect-downs 6 10000)))
                (check "N4: the reaper's rescan delivered every call failure once" (all-noconnection? outs 3) outs)
                (check "N4: ...and every monitor DOWN once" (all-down-once? downs 6) downs))
              (check "N4: the record finished by the rescan while the primary is parked" (records-finished? 8000) (stat 'cleanup-records))
              (resume! t w)
              (no-stray-downs! "N4: the resumed primary found nothing left (no duplicates)" 1000)
              (cleanup! t 'cleanup-before-round)))))

      ;; ---- N11a: competing ordinary completion during cleanup -----------------
      (let ((b1 (open-b BOOT-X 1)))
        (check "N11a: b installed" (not (pair? b1)) b1)
        (expect-up! "N11a: node-up b" 3000)
        (let* ((m-reply-ref #f)
               (mref-mdown (monitor-remote 'b 'mdown))
               (mref-demon (monitor-remote 'b 'demon))
               (victim (spawn (lambda () (let ((m (monitor-remote 'b 'victim))) (receive (x x))))))   ; its owner agent DOWN path
               (short (spawn (lambda () (send main (vector 'call-outcome 'short (guard (e (#t e)) (rcall 'b 'svc '(short) 1500)))))))
               (late  (spawn (lambda () (send main (vector 'call-outcome 'late  (guard (e (#t e)) (rcall 'b 'svc '(late) 30000))))))))
          (let ((fcall (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call) (equal? (cadddr d) '(late)))) 3000)))
            (check "N11a: the peer saw the late call" (and fcall #t))
            (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'mon) (eq? (cadr d) 'victim))) 3000)
            ;; the reaper acts on the publish hint at once, so hold it first: the record
            ;; must stay pending while the competing completions run
            (let* ((tr (arm! 'link-reaper-loop-entry 1))
                   (wr (wait! tr 'link-reaper-loop-entry 5000))
                   (t (arm! 'cleanup-before-round 1)))
              (check "N11a: the reaper is held" (pair? wr) (show wr))
              (plain-peer-close! b1)                        ; primary = link guard; record published
              (let ((w (wait! t 'cleanup-before-round 8000)))
                (check "N11a: the primary parked with the record pending" (and (pair? w) (eqv? (stat 'cleanup-records) 1)) (list (show w) (stat 'cleanup-records)))
                (expect-down! "N11a: node-down b" 6000)
                ;; reinstall b with the SAME boot id so the peer's frames are admitted (5888)
                (let ((b2 (open-b BOOT-X 1)))
                  (check "N11a: b reinstalled (same boot id)" (not (pair? b2)) b2)
                  (expect-up! "N11a: node-up b (reinstalled)" 6000)
                  ;; (1) a late reply for the old pending ref, through the reinstalled peer
                  (when fcall (plain-peer-send! b2 (list 'reply (caddr fcall) (list 'ok 'late-value))))
                  ;; (2) a peer mdown for an old monitor
                  (plain-peer-send! b2 (list 'mdown mref-mdown 'peer-says-down))
                  ;; (3) the short call times out on its own
                  ;; (4) a demonitor of an old monitor
                  (demonitor-remote mref-demon)
                  ;; (5) the victim caller dies: its owner agent's DOWN path removes that watch
                  (kill victim 'n11-victim)
                  (sleep-ms 1500)
                  ;; resume the parked primary: everything it finds is stale or already done
                  (resume! t w)
                  (let ((outs (collect-calls 2 8000)))
                    (check "N11a: the late call got the peer's value once, not noconnection" (equal? (cdr (or (assq 'late outs) '(late . none))) 'late-value) outs)
                    (check "N11a: the short call timed out once, no reply after" (timeout-error? (cdr (or (assq 'short outs) '(short . none)))) outs))
                  (let ((downs (collect-downs 1 4000)))
                    (check "N11a: the mdown monitor was delivered once with the peer's reason" (equal? downs '((mdown . peer-says-down))) downs))
                  (no-stray-downs! "N11a: no noconnection for the demonitored or the victim's watch, no duplicates" 1200)
                  (check "N11a: the record finished with its stale nodes retired" (records-finished? 8000) (stat 'cleanup-records))
                  (check "N11a: owner agents back to base (each stopped exactly once)" (within? 5000 (lambda () (eqv? (stat 'owner-agents) obase))) (stat 'owner-agents) obase)
                  (cleanup! t 'cleanup-before-round)
                  (resume! tr wr) (cleanup! tr 'link-reaper-loop-entry)
                  (plain-peer-close! b2)
                  (expect-down! "N11a: node-down (reinstalled b closed)" 6000)))))))

      ;; ---- N11b: a stale chain node left by a seam is retired silently ---------
      (let ((b1 (open-b BOOT-X 1)))
        (check "N11b: b installed" (not (pair? b1)) b1)
        (expect-up! "N11b: node-up b" 3000)
        (let ((mrefs (arm-monitors! 2))
              (stale-caller (spawn (lambda () (send main (vector 'call-outcome 'stale (guard (e (#t e)) (rcall 'b 'svc '(stale) 3000))))))))
          (check "N11b: the peer saw the call whose slot will be taken" (and (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call))) 3000) #t))
          (check "N11b: the seam took the pending slot, leaving its chain node stale" ($node-stale-chain-node! 'b))
          (let ((t (arm! 'cleanup-stale-retired 1)))
            (kill ($node-link-pid 'b) 'n11b-kill)
            (let ((ws (wait! t 'cleanup-stale-retired 8000)))
              (check "N11b: the stale node was retired silently (counted once)" (pair? ws) (show ws))
              (resume! t ws)
              (cleanup! t 'cleanup-stale-retired))
            (expect-down! "N11b: node-down b" 8000)
            (let ((downs (collect-downs 2 8000)))
              (check "N11b: the live monitors still fired exactly once" (all-down-once? downs 2) downs))
            (no-stray-downs! "N11b: nothing for the stale node" 800)
            (let ((outs (collect-calls 1 6000)))
              (check "N11b: the caller whose slot was taken gets only its own timeout (no noconnection)" (and (pair? outs) (timeout-error? (cdar outs))) outs))
            (check "N11b: the record finished" (records-finished? 8000) (stat 'cleanup-records))))
        (plain-peer-close! b1))

      ;; ---- N12: the hint is lost, the reaper stays alive ----------------------
      (let ((b1 (open-b BOOT-X 1)))
        (check "N12: b installed" (not (pair? b1)) b1)
        (expect-up! "N12: node-up b" 3000)
        (let ((mrefs (arm-monitors! 3)))
          (spawn-callers! 2 main 30000)
          (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call))) 3000)
          (let ((t (arm! 'cleanup-before-hint 1)) (link ($node-link-pid 'b)))
            (plain-peer-close! b1)                         ; primary = link guard
            (let ((w (wait! t 'cleanup-before-hint 8000)))
              (check "N12: the primary parked between publishing and the hint" (and (pair? w) (eq? (cdr w) link)) (show w))
              (when (pair? w) (kill (cdr w) 'n12-primary-killed) (guard (e (#t (void))) (inject-release! t)))
              (cleanup! t 'cleanup-before-hint)
              (expect-down! "N12: node-down b" 6000)
              (let ((t0 (now-ms)) (outs (collect-calls 2 10000)) (downs (collect-downs 3 10000)))
                (check "N12: the reaper finished the record without the hint (calls)" (all-noconnection? outs 2) outs)
                (check "N12: ...(monitors)" (all-down-once? downs 3) downs)
                (display "  [N12] recovered without the hint after ms ") (display (- (now-ms) t0)) (newline))
              (check "N12: the record finished" (records-finished? 8000) (stat 'cleanup-records))))))

      ;; ---- N3': a send raises (allocation failure injected) ------------------
      (for-each
        (lambda (spec)
          (let ((fault (car spec)) (label (cadr spec)))
            (let ((b1 (open-b BOOT-X 1)))
              (check (string-append label ": b installed") (not (pair? b1)) b1)
              (expect-up! (string-append label ": node-up b") 3000)
              (let ((mrefs (arm-monitors! 4)))
                (spawn-callers! 2 main 30000)
                (plain-peer-wait-frame b1 (lambda (d) (and (pair? d) (eq? (car d) 'call))) 3000)
                (inject-arm-fault! fault 1)                 ; the first such send raises once
                (kill ($node-link-pid 'b) 'n3p-kill)
                (expect-down! (string-append label ": node-down b") 8000)
                (let ((outs (collect-calls 2 12000)) (downs (collect-downs 4 12000)))
                  (check (string-append label ": every pending call failed exactly once despite the raise") (all-noconnection? outs 2) outs)
                  (check (string-append label ": every monitor fired DOWN exactly once despite the raise") (all-down-once? downs 4) downs))
                (no-stray-downs! (string-append label ": no duplicate remote-down (no replay)") 800)
                (check (string-append label ": the record finished") (records-finished? 8000) (stat 'cleanup-records))
                (check (string-append label ": owner agents back to base (owner-stop not replayed, not lost)") (within? 5000 (lambda () (eqv? (stat 'owner-agents) obase))) (stat 'owner-agents) obase))
              (plain-peer-close! b1)
              (sleep-ms 300))))
        '((cleanup-send-remote-down "N3'a") (cleanup-send-owner-stop "N3'b") (cleanup-send-reply "N3'c")))

      (check "baseline: rmonitors" (eqv? (stat 'rmonitors) rbase) (stat 'rmonitors) rbase)
      (check "baseline: owner agents" (within? 5000 (lambda () (eqv? (stat 'owner-agents) obase))) (stat 'owner-agents) obase)
      (check "baseline: no cleanup records" (records-finished? 5000) (stat 'cleanup-records)))
    (if (zero? fails)
        (begin (display "ALL CLEANUP-RECORD-EXEC TESTS PASSED\n") (exit 0))
        (begin (display "CLEANUP-RECORD-EXEC VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))))
