#!chezscheme
;; B' cleanup records -- N13, the TLS smoke: N1a on a TLS node (one kill, the
;; last open in this process: an in-process raw TLS client reopened after an
;; in-process kill hits a loopback artefact, see the batch 1 ledger).
(import (chezscheme) (igropyr actor) (igropyr node)
        (only (igropyr libuv) now-ms)
        (igropyr inject-control)
        (only (igropyr tls-core) tls-live-session-count)
        (only (igropyr tcp) tls-live-watcher-count)
        (test tls-raw-client) (test mesh-proof))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (within? ms thunk)
  (let ((deadline (+ (now-ms) ms)))
    (let loop () (cond ((thunk) #t) ((> (now-ms) deadline) #f) (else (sleep-ms 20) (loop))))))
(define dir "/tmp/igropyr-cleanup-record-tls")
(system (string-append "sh igropyr/test/tls-certs.sh " dir " >/dev/null"))
(putenv "SSL_CERT_FILE" (string-append dir "/ca.pem"))
(define (in-dir f) (string-append dir "/" f))
(define port 18740)
(define secret "cleanup-record-tls-secret-0123456789abcdef")
(define probe-boot-id "feedfacefeedface")
(define (stat key) (let ((p (assq key (node-monitor-stats)))) (and p (cdr p))))
(define (frame-bytes datum)
  (let ((o (open-output-string))) (write datum o)
    (let ((b (get-output-string o))) (string->utf8 (string-append (number->string (string-length b)) "\n" b)))))
;; stateful reader over the raw session: keeps leftover bytes across frames
(define leftover "")
(define (read-frame s ms)
  (let loop ((acc leftover))
    (let* ((n (string-length acc))
           (nl (let g ((k 0)) (cond ((= k n) #f) ((char=? (string-ref acc k) #\newline) k) (else (g (+ k 1))))))
           (len (and nl (string->number (substring acc 0 nl)))))
      (if (and len (>= n (+ nl 1 len)))
          (begin (set! leftover (substring acc (+ nl 1 len) n))
                 (read (open-input-string (substring acc (+ nl 1) (+ nl 1 len)))))
          (let ((r (raw-tls-recv! s ms)))
            (if (bytevector? r) (loop (string-append acc (utf8->string r))) (begin (set! leftover acc) r)))))))
(define (join! s)
  (let ((d (read-frame s 4000)))
    (and (pair? d) (eq? (car d) 'challenge)
         (let* ((nonce-a (cadr d)) (bootid-a (cadddr d)) (cb (raw-tls-peer-cb-hash s)))
           (raw-tls-send! s (frame-bytes (list 'hello "b" (v5-proof-d secret nonce-a "b" probe-boot-id 1 "a" bootid-a cb)
                                              "feedfeedfeedfeedfeedfeedfeedfeed" 5 probe-boot-id 1)))
           (let ((w (read-frame s 4000))) (and (pair? w) (eq? (car w) 'welcome)))))))
(define (noconnection? r) (and (vector? r) (eq? (vector-ref r 0) 'rcall-error) (eq? (vector-ref r 1) 'noconnection)))

(start-scheduler
  (lambda ()
    (define main self)
    (register 'main self)
    (node-start! 'a secret port "127.0.0.1"
                 (list (cons 'tls-cert (in-dir "good.pem")) (cons 'tls-key (in-dir "good.key"))))
    (monitor-node 'b)
    (let ((base (list (tls-live-session-count) (tls-live-watcher-count)))
          (rbase (stat 'rmonitors))
          (s (raw-tls-open "127.0.0.1" port "localhost" 5000)))
      (check "N13: TLS session with the node" (not (pair? s)) s)
      (unless (pair? s)
        (check "N13: mesh handshake as b" (join! s))
        (receive (after 3000 (check "N13: node-up b" #f 'timeout)) (`#(node-up b) (check "N13: node-up b" #t)))
        (let ((caller (spawn (lambda () (send main (vector 'call-outcome (guard (e (#t e)) (rcall 'b 'svc '(q) 20000)))))))
              (m (monitor-remote 'b 'svc)))
          (let ((f1 (read-frame s 3000)) (f2 (read-frame s 3000)))
            (check "N13: the peer received the call and mon frames" (and (pair? f1) (pair? f2) (memq (car f1) '(call mon)) (memq (car f2) '(call mon))) (list f1 f2)))
          (let ((link ($node-link-pid 'b)))
            (kill link 'n13-kill)
            (receive (after 6000 (check "N13: node-down b" #f 'timeout)) (`#(node-down b) (check "N13: node-down b" #t)))
            (receive (after 6000 (check "N13: the pending call failed once" #f 'timeout)) (`#(call-outcome ,r) (check "N13: the pending call failed once" (noconnection? r) r)))
            (receive (after 6000 (check "N13: the remote monitor fired once" #f 'timeout)) (`#(remote-down b svc ,reason) (check "N13: the remote monitor fired once" (eq? reason 'noconnection) reason)))
            (receive (after 800 (check "N13: no duplicates" #t)) (`#(remote-down b svc ,r2) (check "N13: no duplicates" #f r2)))
            (check "N13: the record finished" (within? 8000 (lambda () (eqv? (stat 'cleanup-records) 0))) (stat 'cleanup-records))
            (check "N13: rmonitors back to base" (eqv? (stat 'rmonitors) rbase) (stat 'rmonitors) rbase)))
        (raw-tls-close! s)
        (check "N13: sessions and watchers back to baseline" (within? 8000 (lambda () (equal? (list (tls-live-session-count) (tls-live-watcher-count)) base))) (list (tls-live-session-count) (tls-live-watcher-count)) base)))
    (if (zero? fails)
        (begin (display "ALL CLEANUP-RECORD-TLS TESTS PASSED\n") (exit 0))
        (begin (display "CLEANUP-RECORD-TLS VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))))
