#!chezscheme
;; (igropyr css): rule list -> CSS string. No floats: a unit form takes a whole
;; (exact integer), optionally a fraction (exact non-negative integer, rendered
;; with the digits it was written with) and a minimum width (left-padded with
;; zeros BEFORE trailing zeros are stripped). The pins come from the notation's
;; reference test file (its PIN and DETECTOR cells); a transcription that drifts
;; from the reference goes red here.
(import (chezscheme) (igropyr css))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (t label got want) (check label (equal? got want) got want))
(define (r v) (css->string v))
(define (bad? label v) (check label (guard (e (#t #t)) (r v) #f) v))

;; ---- whole values ----------------------------------------------------------
(t "em whole" (r '((x (a (em 1))))) "x{a:1em;}")
(t "px whole" (r '((x (a (px 13))))) "x{a:13px;}")
(t "pct whole" (r '((x (a (pct 50))))) "x{a:50%;}")
(t "vh whole" (r '((x (a (vh 100))))) "x{a:100vh;}")
(t "deg whole" (r '((x (a (deg 120))))) "x{a:120deg;}")
;; ---- fractions: the digits as written; width pads; trailing zeros dropped ----
(t "0.92" (r '((x (a (em 0 92))))) "x{a:0.92em;}")
(t "40 -> .4" (r '((x (a (em 3 40))))) "x{a:3.4em;}")
(t "1.15" (r '((x (a (em 1 15))))) "x{a:1.15em;}")
(t "13.5px" (r '((x (a (px 13 50))))) "x{a:13.5px;}")
(t "0.3rem" (r '((x (a (rem 0 30))))) "x{a:0.3rem;}")
(t "0.625" (r '((x (a (em 0 625))))) "x{a:0.625em;}")
(t "one digit means tenths (3.4, not 3.04)" (r '((x (a (em 3 4))))) "x{a:3.4em;}")
(t "0.2" (r '((x (a (em 0 2))))) "x{a:0.2em;}")
(t "13.5 from a one-digit fraction" (r '((x (a (px 13 5))))) "x{a:13.5px;}")
(t "width 2 pads: 3.04" (r '((x (a (em 3 4 2))))) "x{a:3.04em;}")
(t "width 2 pads: 0.02" (r '((x (a (em 0 2 2))))) "x{a:0.02em;}")
(t "width is a minimum" (r '((x (a (em 0 625 2))))) "x{a:0.625em;}")
(t "padding before stripping: 50/3 is 0.05" (r '((x (a (em 0 50 3))))) "x{a:0.05em;}")
(t "padding before stripping: 100/4 is 1.01" (r '((x (a (em 1 100 4))))) "x{a:1.01em;}")
(t "40/2 is 0.4" (r '((x (a (em 0 40 2))))) "x{a:0.4em;}")
(t "40/1 is 0.4" (r '((x (a (em 0 40 1))))) "x{a:0.4em;}")
(t "625/4 is 0.0625" (r '((x (a (em 0 625 4))))) "x{a:0.0625em;}")
(t "zero fraction: no decimal point (1em)" (r '((x (a (em 1 0))))) "x{a:1em;}")
(t "zero fraction: 0em" (r '((x (a (em 0 0))))) "x{a:0em;}")
(t "zero fraction with a width: still no point" (r '((x (a (em 1 0 3))))) "x{a:1em;}")
(t "a long fraction keeps every digit" (r '((x (a (em 0 12345678901234567891))))) "x{a:0.12345678901234567891em;}")
(t "...except a trailing zero" (r '((x (a (em 0 12345678901234567890))))) "x{a:0.1234567890123456789em;}")
(t "the sign lives in the whole part" (r '((x (a (em -3 4))))) "x{a:-3.4em;}")
(t "negative whole with a padded fraction" (r '((x (a (em -3 4 2))))) "x{a:-3.04em;}")
(t "a width of zero says the same as leaving it out" (r '((x (a (em 3 4 0))))) "x{a:3.4em;}")
;; ---- operands are checked, not trusted --------------------------------------
(bad? "no operand" '((x (a (em)))))
(bad? "four operands (the fourth used to be dropped silently)" '((x (a (em 1 2 3 4)))))
(bad? "a ratio is not a digit string" '((x (a (em 1 1/2)))))
(bad? "a string fraction" '((x (a (em 1 "5")))))
(bad? "a float width" '((x (a (em 1 5 2.0)))))
(bad? "a negative width" '((x (a (em 1 5 -1)))))
(bad? "a negative fraction (would have rendered 0.-5)" '((x (a (em 0 -5)))))
(bad? "a float scalar" '((x (a 1.5))))
(bad? "a bad selector" '((1 (a 1))))
(bad? "a bad value" '((x (a #t))))
;; ---- every unit ------------------------------------------------------------
(for-each
  (lambda (u suf)
    (t (string-append "unit " (symbol->string u)) (r `((x (a (,u 1 4))))) (string-append "x{a:1.4" suf ";}")))
  '(px em rem pct vh vw vmin vmax fr deg s ms ch ex)
  '("px" "em" "rem" "%" "vh" "vw" "vmin" "vmax" "fr" "deg" "s" "ms" "ch" "ex"))
(t "pct with width" (r '((x (a (pct 1 4 2))))) "x{a:1.04%;}")
(t "ms with width" (r '((x (a (ms 1 4 2))))) "x{a:1.04ms;}")
;; ---- bare integers, decimals, alpha ------------------------------------------
(t "bare integer and a unitless decimal" (r '((body (margin 0) (line-height (dec 1 60))))) "body{margin:0;line-height:1.6;}")
(t "dec 0 6 is 0.6" (r '((x (a (dec 0 6))))) "x{a:0.6;}")
(t "dec 0 6 2 is 0.06" (r '((x (a (dec 0 6 2))))) "x{a:0.06;}")
(t "dec with a zero fraction: no bare dot" (r '((x (a (dec 1 0 3))))) "x{a:1;}")
(t "dec 0 0 is 0" (r '((x (a (dec 0 0))))) "x{a:0;}")
;; ---- variables, selectors, compound values, calc, colours ---------------------
(t "custom properties on :root" (r '((:root (--bg "#f2f4fa") (--lapis "#1550c4")))) ":root{--bg:#f2f4fa;--lapis:#1550c4;}")
(t "string selector, var(), em fraction" (r '((".nav a" (color (var dim)) (font-size (em 0 92))))) ".nav a{color:var(--dim);font-size:0.92em;}")
(t "compound value and a multi-value declaration" (r '((.box (border (px 1) solid (var line)) (padding (em 1 10) (em 1 20)))))
   ".box{border:1px solid var(--line);padding:1.1em 1.2em;}")
(t "calc and rgba" (r '((.x (width (calc (pct 100) - (em 2))) (box-shadow 0 (px 1) (px 3) (rgba 16 20 42 (dec 0 6 2))))))
   ".x{width:calc(100% - 2em);box-shadow:0 1px 3px rgba(16,20,42,0.06);}")
(t "rgb" (r '((x (color (rgb 1 2 3))))) "x{color:rgb(1,2,3);}")
(t "a symbol value renders as its name" (r '((x (display none) (position inherit)))) "x{display:none;position:inherit;}")
(t "a string value passes through" (r '((x (content "\"q\"")))) "x{content:\"q\";}")
;; ---- nesting -------------------------------------------------------------------
(t "@media nesting" (r '((@media "(max-width: 42em)" (".nav-links" (gap (em 1)) (font-size (em 0 88))))))
   "@media (max-width: 42em){.nav-links{gap:1em;font-size:0.88em;}}")
(t "@keyframes nesting" (r '((@keyframes spin (from (transform "rotate(0)")) (to (transform "rotate(360deg)")))))
   "@keyframes spin{from{transform:rotate(0);}to{transform:rotate(360deg);}}")
(t "@supports nesting" (r '((@supports "(display: grid)" (.g (display grid)))))
   "@supports (display: grid){.g{display:grid;}}")
;; ---- composition, palette, num->css -------------------------------------------
(let ((base '((body (margin 0)))) (page '((h1 (font-size (em 3))))))
  (t "a stylesheet is a list: append composes" (r (append base page)) "body{margin:0;}h1{font-size:3em;}"))
(t "palette->root builds the :root rule" (palette->root '((ink "#14203a") (bg "#f2f4fa"))) '(:root (--ink "#14203a") (--bg "#f2f4fa")))
(t "palette->root renders" (r (list (palette->root '((ink "#14203a") (bg "#f2f4fa"))))) ":root{--ink:#14203a;--bg:#f2f4fa;}")
(t "num->css: exact integer and string" (list (num->css 650) (num->css "#fff")) '("650" "#fff"))
(check "num->css refuses a float" (guard (e (#t #t)) (num->css 1.5) #f))
(t "an empty stylesheet" (r '()) "")

(if (zero? fails)
    (begin (display "ALL CSS TESTS PASSED\n") (exit 0))
    (begin (display "CSS VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))
