#!chezscheme
;; Child processes -- seam-driven fault cells (proc-spawn design v4-v8 §5; codex
;; pre-review 01a08dfe folded: counted points are armed with a never-firing
;; barrier so their hits count; the deliberate index leaks of P21c/P27/P29 are
;; carried as an expected offset so every later baseline stays exact).
;;   P15  the exit is delivered exactly once for the returned proc; no-row path never taken
;;        (the region-split red proof is a separate mutation driver)
;;   P18  the orphan path: uv_spawn's result overridden to -1 with a real child started
;;        (its row is visible right after the call, then reaped); a publication fault
;;   P21  callback allocation faults: exit notification; process-close unindex
;;   P24  the failed-spawn queue repair (F13): (a) the real error: path via a bogus stdio
;;        stream, (b) the simulated queue removal on an active orphan; the neighbours are
;;        closed and replaced BEFORE the loop runs the failed handle's close
;;   P25  the process handle block is retained until the row retires (per-address free log: proc-handles-freed)
;;   P27  rollback faults: second pipe init skipped, read-start negative, publish fault,
;;        index fault (row kept), recover-index fault (row kept, unindexed once), rollback
;;        unindex fault, orphan publish fault (re-raised; no-row path; no zombie)
;;   P28  shutdown faults: registration raise, negative submission (skipped call)
;;   P29  close-callback containment: unindex fault on a pipe conn
;;   P30  write-block ownership, plaintext: registration fault on the queued path (pipe and
;;        TCP conn), state rejection and negative submission release points
(import (chezscheme) (igropyr actor) (igropyr tcp)
        (only (igropyr libuv) now-ms uv-live-handle-count uv-strerror)
        (igropyr inject-control))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (within? ms thunk)
  (let ((deadline (+ (now-ms) ms)))
    (let loop () (cond ((thunk) #t) ((> (now-ms) deadline) #f) (else (sleep-ms 20) (loop))))))
(define (spawn-sh cmd . opts) (apply proc-spawn! "/bin/sh" (list "sh" "-c" cmd) opts))
(define (failed? r) (and (pair? r) (eq? (car r) 'failed)))
(define (wait-exit p ms) (receive (after ms 'timeout) (`#(proc-exit ,@p ,code ,signal) (cons code signal))))
(define (cat bvs)
  (let* ((n (apply + (map bytevector-length bvs))) (out (make-bytevector n)))
    (let loop ((bvs bvs) (o 0))
      (unless (null? bvs)
        (bytevector-copy! (car bvs) 0 out o (bytevector-length (car bvs)))
        (loop (cdr bvs) (+ o (bytevector-length (car bvs))))))
    out))
(define (collect p stream ms)
  (let ((deadline (+ (now-ms) ms)))
    (let loop ((acc '()))
      (receive (after (max 1 (- deadline (now-ms))) (cons 'partial (cat (reverse acc))))
        (`#(proc-data ,@p ,@stream ,bv) (loop (cons bv acc)))
        (`#(proc-eof ,@p ,@stream) (cat (reverse acc)))))))
;; the deliberate index leaks (P21c, P27 rollback-unindex, P29) are NOT permanent:
;; unindex-owner! removes every entry matching (kind . key) and handle addresses are
;; recycled at once, so a later child's pipe close can take a stale entry with it
;; and a cell can reclaim an older one while leaking its own (measured by the code
;; session). So each leak cell runs under a FRESH OWNER process: the +1 is asserted
;; while that owner lives, and killing it afterwards removes its entries through the
;; owner-death traversal, which restores the exact five-count baseline.
(define (base) (list (uv-live-handle-count) (conn-count) (pipe-conn-count) (proc-count) (uv-owner-index-count)))
(define (back-to-base! label b ms) (check label (within? ms (lambda () (equal? (base) b))) (base) b))
;; a fresh owner that spawns as itself and forwards every proc message to main
(define (owned-spawn! main cmd)
  (spawn (lambda ()
           (let ((p (spawn-sh cmd)))
             (send main (vector 'owned p))
             (let loop () (receive (m (send main m) (loop))))))))
(define (owned! main cmd) (let ((o (owned-spawn! main cmd))) (receive (after 3000 (cons o #f)) (`#(owned ,p) (cons o p)))))
;; the last spawned child's pid (test seam), for an orphan the caller never sees
(define (child-state pid)
  (let* ((f "/tmp/igropyr-ps-state.txt")
         (r (system (string-append "ps -o stat= -p " (number->string pid) " > " f " 2>/dev/null"))))
    (let ((t (guard (e (#t "")) (call-with-input-file f get-string-all))))
      (cond ((not (eqv? r 0)) 'gone)
            ((= (string-length t) 0) 'gone)
            ((char=? (string-ref t 0) #\Z) 'zombie)
            (else 'live)))))
(define (reaped? pid) (eq? (child-state pid) 'gone))
(define (count! point) (inject-arm-barrier! point 1000000 60000))
(define (hits point) (or (inject-hits point) 0))
(define (uncount! t) (guard (e (#t (void))) (inject-release! t)))
(define (stat key) (let ((a (assq key (proc-stats)))) (and a (cdr a))))
(define (drain! ms) (let loop () (receive (after ms (void)) (`#(proc-data ,p ,s ,bv) (loop)) (`#(proc-eof ,p ,s) (loop)) (`#(proc-exit ,p ,c ,g) (loop)) (`#(proc-error ,p ,s ,n) (loop)))))
(define (finish! p) (when (proc? p) (guard (e (#t (void))) (proc-kill! p 9)) (wait-exit p 3000) (proc-close! p) (drain! 300)))
(define (ps-has? marker) (eqv? 0 (system (string-append "ps -axo stat=,command= | grep -v grep | grep -q '" marker "'"))))
(define mac? (and (memq (machine-type) '(tarm64osx ta6osx i3osx a6osx arm64osx)) #t))
(define port 18810)
;; P24's neighbours: two listeners created before the failing spawn, closed right after it
;; returns and replaced by two more, all before this process yields to the loop -- so the
;; failed handle's queue node sees changed neighbours when uv__finish_close removes it
(define (with-neighbours thunk)
  (let ((l1 (tcp-listen! "127.0.0.1" port 16 (lambda (c) (void))))
        (l2 (tcp-listen! "127.0.0.1" (+ port 1) 16 (lambda (c) (void)))))
    ;; the failed spawn and the neighbour replacement share one region: no timer
    ;; preemption can let the loop run the failed handle's close in between
    (let ((rl (with-interrupts-disabled
                (let ((r (thunk)))
                  (tcp-stop-listen! l1) (tcp-stop-listen! l2)
                  (list r
                        (tcp-listen! "127.0.0.1" (+ port 2) 16 (lambda (c) (void)))
                        (tcp-listen! "127.0.0.1" (+ port 3) 16 (lambda (c) (void))))))))
      (sleep-ms 100)
      (tcp-stop-listen! (cadr rl)) (tcp-stop-listen! (caddr rl))
      (car rl))))

(start-scheduler
  (lambda ()
    (define main self)
    (register 'main self)
    ;; inject-disarm! between cells clears every armed row, counted points included, so
    ;; each cell arms the points it reads and reads them before its disarm
    (let ((b0 (base)))

      ;; ---- P15: exactly one exit for the returned proc ----------------------------------
      (let ((p (begin (count! 'proc-exit-cb-no-row) (spawn-sh "true"))))
        (check "P15: the exit is for the returned proc" (equal? (wait-exit p 3000) '(0 . 0)))
        (receive (after 500 (check "P15: exactly one exit" #t)) (`#(proc-exit ,@p ,c ,s) (check "P15: exactly one exit" #f (list c s))))
        (check "P15: the no-row path was never taken" (eqv? (hits 'proc-exit-cb-no-row) 0) (hits 'proc-exit-cb-no-row))
        (drain! 300)
        (back-to-base! "P15: counts back" b0 3000))
      (inject-disarm!)

      ;; ---- P18: the orphan path ---------------------------------------------------------------
      (let ((h0 (begin (count! 'proc-exit-cb-no-row) 0)))
        (inject-arm-return! 'proc-uv-spawn-result -1 1)
        (let* ((rr (with-interrupts-disabled (let ((r (spawn-sh "exec sleep 7118"))) (cons r (proc-count)))))
               (r (car rr)) (rows (cdr rr)) (pid ($proc-last-spawned-pid)))
          (check "P18: the caller gets a failure although a child was started" (failed? r) r)
          (check "P18: the orphan's row is visible right after the call (a child WAS started and counted)" (eqv? rows (+ (list-ref b0 3) 1)) rows)
          (check "P18: the override fired once" (eqv? (hits 'proc-uv-spawn-result) 1))
          (check "P18: the OS child (pid from the seam) is gone and reaped within 2 s, not a zombie" (and pid (within? 2000 (lambda () (reaped? pid)))) pid (and pid (child-state pid)))
          (back-to-base! "P18: counts back" b0 3000)
          (check "P18: the orphan's exit went through its row, not the no-row path" (eqv? (hits 'proc-exit-cb-no-row) h0) (hits 'proc-exit-cb-no-row))
          (drain! 300)))
      (inject-disarm!)
      (inject-arm-fault! 'proc-publish-fail 1)
      (let* ((rr (with-interrupts-disabled (let ((r (guard (e (#t (cons 'raised e))) (spawn-sh "exec sleep 7119")))) (cons r (proc-count)))))
             (r (car rr)) (pid ($proc-last-spawned-pid)))
        (check "P18 publish: the condition reaches the caller" (and (pair? r) (eq? (car r) 'raised)) (if (pair? r) (car r) r))
        (check "P18 publish: the fault fired once" (eqv? (hits 'proc-publish-fail) 1))
        (check "P18 publish: the orphan row is present right after the call" (eqv? (cdr rr) (+ (list-ref b0 3) 1)) (cdr rr))
        (check "P18 publish: the child was killed and reaped (pid from the seam)" (and pid (within? 2000 (lambda () (reaped? pid)))) pid (and pid (child-state pid)))
        (back-to-base! "P18 publish: counts back" b0 3000)
        (drain! 300))
      (inject-disarm!)

      ;; ---- P21: callback allocation faults -------------------------------------------------------
      (let ((p (begin (inject-arm-fault! 'proc-exit-notify 1) (spawn-sh "true"))))
        (check "P21 exit-notify: no exit message (the notification raised inside its guard)" (eq? (wait-exit p 1500) 'timeout))
        (check "P21 exit-notify: the fault fired once" (eqv? (hits 'proc-exit-notify) 1))
        (check "P21 exit-notify: the child was still invalidated (pid #f, not running)" (within? 2000 (lambda () (and (not (proc-pid p)) (not (eq? (proc-state p) 'running))))) (list (proc-pid p) (proc-state p)))
        (check "P21 exit-notify: closed" (within? 3000 (lambda () (eq? (proc-state p) 'closed))) (proc-state p))
        (drain! 300)
        (back-to-base! "P21 exit-notify: counts back" b0 3000))
      (inject-disarm!)
      (inject-arm-fault! 'proc-close-unindex 1)
      (let* ((op (owned! main "true")) (owner (car op)) (p (cdr op)))
        (check "P21 close-unindex: spawned under a fresh owner" (proc? p) p)
        (check "P21 close-unindex: exit" (equal? (wait-exit p 3000) '(0 . 0)))
        (drain! 500)
        (check "P21 close-unindex: the fault fired (arrived at least once)" (>= (hits 'proc-close-unindex) 1) (hits 'proc-close-unindex))
        (check "P21 close-unindex: the row retired and the handle was freed although unindex raised"
               (within? 3000 (lambda () (and (eq? (proc-state p) 'closed) (equal? (list-head (base) 4) (list-head b0 4))))) (list (proc-state p) (base)))
        (check "P21 close-unindex: exactly one index entry leaked while its owner lives" (eqv? (uv-owner-index-count) (+ (list-ref b0 4) 1)) (uv-owner-index-count) (list-ref b0 4))
        (kill owner 'p21-owner-done)
        (back-to-base! "P21 close-unindex: the owner's death took the leaked entry; exact baseline" b0 3000))
      (inject-disarm!)

      ;; ---- P24: the F13 repair with neighbours ---------------------------------------------------
      (let ((lk0 (begin (count! 'proc-f13-linked) 0)) (rl0 (begin (count! 'proc-f13-relinked) 0)))
        (inject-arm-return! 'proc-stdio-bogus-stream #t 1)
        (let ((r (with-neighbours (lambda () (spawn-sh "true")))))
          (check "P24a: a non-pipe stdio stream fails uv_spawn before any fork (EINVAL)" (failed? r) r)
          (check "P24a: the seam fired once" (eqv? (hits 'proc-stdio-bogus-stream) 1)))
        (drain! 300)
        (let ((lk (- (hits 'proc-f13-linked) lk0)) (rl (- (hits 'proc-f13-relinked) rl0)))
          (check "P24a: exactly one repair branch ran" (= (+ lk rl) 1) (list lk rl))
          (check (if mac? "P24a: on macOS (libuv 1.50) the handle was still linked" "P24a: on FreeBSD (libuv 1.52) the handle had been removed and was relinked")
                 (if mac? (= lk 1) (= rl 1)) (list lk rl)))
        (back-to-base! "P24a: no crash, handles and counts exact after neighbour churn" b0 3000))
      (inject-disarm!)
      (let ((rl0 (begin (count! 'proc-f13-relinked) 0)))
        (inject-arm-return! 'proc-uv-spawn-result -1 1)
        (inject-arm-return! 'proc-simulate-queue-removal #t 1)
        (let ((r (with-neighbours (lambda () (spawn-sh "exec sleep 7124")))))
          (check "P24b: active orphan with its queue node removed: failure returned" (failed? r) r)
          (check "P24b: both seams fired once" (and (eqv? (hits 'proc-uv-spawn-result) 1) (eqv? (hits 'proc-simulate-queue-removal) 1))))
        (let ((pid ($proc-last-spawned-pid)))
          (check "P24b: the orphan was killed and reaped (pid from the seam)" (and pid (within? 2000 (lambda () (and (eqv? (proc-count) (list-ref b0 3)) (reaped? pid))))) (proc-count) pid))
        (drain! 300)
        (check "P24b: the relinked branch ran once" (eqv? (- (hits 'proc-f13-relinked) rl0) 1) (hits 'proc-f13-relinked))
        (back-to-base! "P24b: no crash, handles and counts exact" b0 3000))
      (inject-disarm!)

      ;; ---- P25: the handle block is retained until the row retires --------------------------
      (let* ((log0 (proc-handles-freed))
             (freed-since (lambda () (let ((now (proc-handles-freed)))
                                       ;; the log grows at one end; take whichever end is new
                                       (let ((k (- (length now) (length log0))))
                                         (cond ((<= k 0) '())
                                               ((equal? (list-tail now k) log0) (list-head now k))
                                               (else (list-tail now (length log0))))))))
             (a (spawn-sh "read x; echo x; exit 0")))
        (proc-read-stop! a 'stdout)
        (proc-write! a (string->utf8 "go\n"))
        (check "P25: A exited" (equal? (wait-exit a 3000) '(0 . 0)))
        ;; the process close callback ran: of A's four handles only the read-stopped stdout
        ;; remains (stdin was closed by the exit, stderr reached EOF and closed itself);
        ;; base + 2 would mean the process handle is still open
        (check "P25: A's process handle closed (live handles = base + 1: the read-stopped stdout only), row still open"
               (within? 2000 (lambda () (and (eq? (proc-state a) 'exited) (eqv? (stat 'exited-unclosed) 1) (eqv? (uv-live-handle-count) (+ (list-ref b0 0) 1))))) (list (proc-state a) (stat 'exited-unclosed) (uv-live-handle-count) (list-ref b0 0)))
        (check "P25: A's block is not among the addresses freed since A was allocated" (not (memv (proc-handle a) (freed-since))))
        (let ((later (let loop ((i 0) (acc '())) (if (= i 100) acc (loop (+ i 1) (cons (spawn-sh "true") acc))))))
          (let ((exits (map (lambda (p) (wait-exit p 5000)) later)))
            (check "P25: 100 later children each exited 0 for their own proc" (for-all (lambda (e) (equal? e '(0 . 0))) exits) (length (filter (lambda (e) (not (equal? e '(0 . 0)))) exits))))
          (drain! 500)
          (check "P25: the later children closed" (within? 5000 (lambda () (eqv? (proc-count) (+ (list-ref b0 3) 1)))) (proc-count)))
        (check "P25: proc-table[handle A] is still A (identity)" (eq? ($proc-table-ref (proc-handle a)) a))
        (check "P25: A's block still not freed while its row lives (100 later blocks were)" (and (not (memv (proc-handle a) (freed-since))) (>= (length (freed-since)) 100)) (length (freed-since)))
        (proc-read-start! a 'stdout)
        (check "P25: A's data and EOF after read-start" (equal? (collect a 'stdout 3000) (string->utf8 "x\n")))
        (collect a 'stderr 2000)
        (check "P25: A closed and its block freed exactly once" (within? 3000 (lambda () (and (eq? (proc-state a) 'closed) (= 1 (length (filter (lambda (x) (eqv? x (proc-handle a))) (freed-since))))))) (list (proc-state a)))
        (back-to-base! "P25: counts back" b0 3000))

      ;; ---- P27: rollback faults ------------------------------------------------------------
      (inject-arm-return! 'proc-alloc-pipe-fail -1 2)
      (let ((r (spawn-sh "true")))
        (check "P27 pipe-init: the SECOND pipe init skipped -> failure returned (synthetic pre-initialisation failure)" (failed? r) r)
        (check "P27 pipe-init: the seam fired on its second occurrence" (eqv? (hits 'proc-alloc-pipe-fail) 2))
        (check "P27 pipe-init: nothing published; the first pipe's close ran; everything released" (within? 2000 (lambda () (equal? (base) b0))) (base) b0))
      (inject-disarm!)
      (inject-arm-return! 'proc-read-start-result -1 1)
      (let* ((rr (with-interrupts-disabled (let ((r (spawn-sh "exec sleep 7127"))) (cons r (proc-count))))) (r (car rr)) (pid ($proc-last-spawned-pid)))
        (check "P27 read-start: failure returned" (failed? r) r)
        (check "P27 read-start: the seam fired once" (eqv? (hits 'proc-read-start-result) 1))
        (check "P27 read-start: the orphan row is present right after the call" (eqv? (cdr rr) (+ (list-ref b0 3) 1)) (cdr rr))
        (check "P27 read-start: the child was killed and reaped (pid from the seam)" (and pid (within? 2000 (lambda () (reaped? pid)))) pid)
        (back-to-base! "P27 read-start: active rollback, counts back" b0 3000)
        (drain! 300))
      (inject-disarm!)
      (inject-arm-fault! 'proc-publish-index-fail 1)
      (let* ((rr (with-interrupts-disabled (let ((r (guard (e (#t 'raised)) (spawn-sh "exec sleep 7128")))) (cons r (proc-count))))) (r (car rr)) (pid ($proc-last-spawned-pid)))
        (check "P27 index: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 index: the fault fired once" (eqv? (hits 'proc-publish-index-fail) 1))
        (check "P27 index: the row was KEPT (orphan in proc-count right after the call)" (eqv? (cdr rr) (+ (list-ref b0 3) 1)) (cdr rr))
        (check "P27 index: reaped (pid from the seam)" (and pid (within? 2000 (lambda () (reaped? pid)))) pid)
        (back-to-base! "P27 index: reaped through its row, counts back" b0 3000)
        (drain! 300))
      (inject-disarm!)
      (inject-arm-fault! 'proc-recover-index-fail 1)
      (inject-arm-fault! 'proc-publish-index-fail 1)
      (let* ((u0 (begin (count! 'proc-orphan-unindexed) 0))
             (rr (with-interrupts-disabled (let ((r (guard (e (#t 'raised)) (spawn-sh "exec sleep 7129")))) (cons r (proc-count)))))
             (r (car rr)) (pid ($proc-last-spawned-pid)))
        (check "P27 recover: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 recover: both faults fired once" (and (eqv? (hits 'proc-recover-index-fail) 1) (eqv? (hits 'proc-publish-index-fail) 1)))
        (check "P27 recover: the row was kept (proc-count) without its owner entry (counted once)" (and (eqv? (cdr rr) (+ (list-ref b0 3) 1)) (eqv? (hits 'proc-orphan-unindexed) (+ u0 1))) (list (cdr rr) (hits 'proc-orphan-unindexed)))
        (check "P27 recover: reaped (pid from the seam)" (and pid (within? 2000 (lambda () (reaped? pid)))) pid)
        (back-to-base! "P27 recover: counts back" b0 3000)
        (drain! 300))
      (inject-disarm!)
      (inject-arm-fault! 'proc-rollback-unindex 1)
      (inject-arm-fault! 'proc-publish-fail 1)
      (let* ((owner (spawn (lambda ()
                             (send main (vector 'owned-outcome (guard (e (#t 'raised)) (spawn-sh "exec sleep 7130" (cons 'owner self)))))
                             (let loop () (receive (m (loop)))))))
             (r (receive (after 5000 'no-outcome) (`#(owned-outcome ,r) r)))
             (pid ($proc-last-spawned-pid)))
        (check "P27 rollback-unindex: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 rollback-unindex: both faults fired once" (and (eqv? (hits 'proc-rollback-unindex) 1) (eqv? (hits 'proc-publish-fail) 1)))
        (check "P27 rollback-unindex: reaped (pid from the seam)" (and pid (within? 2000 (lambda () (reaped? pid)))) pid)
        (check "P27 rollback-unindex: the rest of the rollback ran (handles, conns, procs back)"
               (within? 3000 (lambda () (equal? (list-head (base) 4) (list-head b0 4)))) (base) b0)
        (check "P27 rollback-unindex: exactly one index entry leaked while its owner lives" (eqv? (uv-owner-index-count) (+ (list-ref b0 4) 1)) (uv-owner-index-count) (list-ref b0 4))
        (kill owner 'p27-owner-done)
        (back-to-base! "P27 rollback-unindex: the owner's death took the leaked entry; exact baseline" b0 3000)
        (drain! 300))
      (inject-disarm!)
      (let ((h0 (begin (count! 'proc-exit-cb-no-row) 0)))
        (inject-arm-fault! 'proc-orphan-publish 1)
        (inject-arm-return! 'proc-uv-spawn-result -1 1)
        (let ((r (guard (e (#t 'raised)) (spawn-sh "exec sleep 7131"))))
          (check "P27 orphan-publish: the condition is re-raised to the caller" (eq? r 'raised) r)
          (check "P27 orphan-publish: both seams fired once" (and (eqv? (hits 'proc-orphan-publish) 1) (eqv? (hits 'proc-uv-spawn-result) 1)))
          (check "P27 orphan-publish: no row (proc-count at base), handle kept registered" (eqv? (proc-count) (list-ref b0 3)) (proc-count))
          (check "P27 orphan-publish: the exit took the no-row path" (within? 3000 (lambda () (eqv? (hits 'proc-exit-cb-no-row) (+ h0 1)))) (hits 'proc-exit-cb-no-row))
          (let ((pid ($proc-last-spawned-pid)))
            (check "P27 orphan-publish: the child (pid from the seam) is gone, not a zombie" (and pid (within? 3000 (lambda () (reaped? pid)))) pid (and pid (child-state pid))))
          (back-to-base! "P27 orphan-publish: freed by the no-row close path, counts back" b0 3000)
          (drain! 300)))
      (inject-disarm!)

      ;; ---- P28: shutdown faults ----------------------------------------------------------------
      (let ((p (spawn-sh "exec cat")))
        (inject-arm-fault! 'proc-shutdown-register 1)
        (let ((r (guard (e (#t 'raised)) (proc-stdin-close! p))))
          (check "P28 register: the condition reaches the caller" (eq? r 'raised) r)
          (check "P28 register: the fault fired once" (eqv? (hits 'proc-shutdown-register) 1))
          (check "P28 register: the pipe was closed, the request freed (pending 0, live requests 0)" (within? 2000 (lambda () (and (not (proc-stdin p)) (eqv? (stat 'shutdown-pending) 0) (eqv? (stat 'shutdown-requests-live) 0)))) (list (proc-stdin p) (stat 'shutdown-pending) (stat 'shutdown-requests-live)))
          (check "P28 register: cat exits at EOF" (equal? (wait-exit p 3000) '(0 . 0)))
          (drain! 300)
          (back-to-base! "P28 register: counts back" b0 3000)))
      (inject-disarm!)
      (let ((p (spawn-sh "exec cat")) (e0 (or (stat 'shutdown-immediate-errors) 0)))
        (inject-arm-return! 'proc-uv-shutdown-result -1 1)
        (check "P28 neg: proc-stdin-close! -> #t (the stream is closing either way)" (proc-stdin-close! p))
        (check "P28 neg: the seam fired once (the raw call was skipped)" (eqv? (hits 'proc-uv-shutdown-result) 1))
        (check "P28 neg: counted as an immediate error, request freed (live requests 0)" (within? 2000 (lambda () (and (eqv? (stat 'shutdown-immediate-errors) (+ e0 1)) (eqv? (stat 'shutdown-pending) 0) (eqv? (stat 'shutdown-requests-live) 0)))) (list (stat 'shutdown-immediate-errors) (stat 'shutdown-pending) (stat 'shutdown-requests-live)))
        (check "P28 neg: the pipe closed, cat exits" (equal? (wait-exit p 3000) '(0 . 0)))
        (drain! 300)
        (back-to-base! "P28 neg: counts back" b0 3000))
      (inject-disarm!)

      ;; ---- P29: close-callback containment ------------------------------------------------------
      (inject-arm-fault! 'conn-close-unindex 1)
      (let* ((op (owned! main "true")) (owner (car op)) (p (cdr op)))
        (check "P29: spawned under a fresh owner with the fault armed first" (proc? p) p)
        (check "P29: exit" (equal? (wait-exit p 3000) '(0 . 0)))
        (drain! 500)
        (check "P29: the fault fired once at the first of the three pipe closes (three arrivals)" (eqv? (hits 'conn-close-unindex) 3) (hits 'conn-close-unindex))
        (check "P29: the handle was freed, the pipe field cleared and the row retired although unindex raised"
               (within? 3000 (lambda () (and (eq? (proc-state p) 'closed) (equal? (list-head (base) 4) (list-head b0 4))))) (list (proc-state p) (base)))
        (check "P29: exactly one index entry leaked while its owner lives" (eqv? (uv-owner-index-count) (+ (list-ref b0 4) 1)) (uv-owner-index-count) (list-ref b0 4))
        (kill owner 'p29-owner-done)
        (back-to-base! "P29: the owner's death took the leaked entry; exact baseline" b0 3000))
      (inject-disarm!)

      ;; ---- P30: write-block ownership, plaintext ----------------------------------------------------
      (let ((p (spawn-sh "exec sleep 5")) (w0 (write-blocks-live-count)) (t0 (write-table-size))
            (rf (count! 'write-block-released-register-fail)))
        (check "P30 pipe: premise -- saturated (1 MiB queued)" (and (proc-write! p (make-bytevector 1048576 8)) (> (proc-queued p) 0)) (proc-queued p))
        (let ((q0 (proc-queued p)) (w1 (write-blocks-live-count)) (t1 (write-table-size)))
          (inject-arm-fault! 'write-register-oom 1)
          (let ((r (guard (e (#t 'raised)) (proc-write! p (make-bytevector 65536 9)))))
            (check "P30 pipe: the registration fault reaches the caller" (eq? r 'raised) r)
            (check "P30 pipe: the fault fired once and the release point was hit once" (and (eqv? (hits 'write-register-oom) 1) (eqv? (hits 'write-block-released-register-fail) 1)) (list (hits 'write-register-oom) (hits 'write-block-released-register-fail)))
            (check "P30 pipe: the block was freed (live blocks back to the backlog's count) and the table unchanged" (and (eqv? (write-blocks-live-count) w1) (eqv? (write-table-size) t1)) (list (write-blocks-live-count) w1 (write-table-size) t1))
            (check "P30 pipe: queued refunded to the backlog's charge" (eqv? (proc-queued p) q0) (list (proc-queued p) q0))))
        (uncount! rf)
        (inject-disarm!)
        (let ((st #f))
          (check "P30 pipe: the wrapper is still usable: a following write is accepted" (proc-write! p (make-bytevector 16 1) (lambda (s) (set! st s))))
          (proc-close! p)
          (check "P30 pipe: ...and settles (cancelled by the close, status negative) with queued 0" (within? 3000 (lambda () (and st (< st 0) (eqv? (proc-queued p) 0)))) st (proc-queued p)))
        (proc-kill! p 9) (wait-exit p 3000) (drain! 300)
        (check "P30 pipe: live blocks and table back after the close" (within? 2000 (lambda () (and (eqv? (write-blocks-live-count) w0) (eqv? (write-table-size) t0)))) (list (write-blocks-live-count) (write-table-size)))
        (back-to-base! "P30 pipe: counts back" b0 3000))
      ;; the same on an ordinary TCP connection: registration fault, state rejection, negative submission
      (let* ((w0 (write-blocks-live-count)) (t0 (write-table-size))
             (srv #f)
             (l (tcp-listen! "127.0.0.1" (+ port 10) 16 (lambda (c) (set! srv c))))
             (cli (begin (tcp-connect! "127.0.0.1" (+ port 10) main) (receive (after 3000 #f) (`#(tcp-connected ,c) c))))
             (rf (count! 'write-block-released-register-fail)))
        (check "P30 tcp: premise -- a connection pair" (and cli (within? 2000 (lambda () srv))))
        (inject-arm-fault! 'write-register-oom 1)
        (let ((r (guard (e (#t 'raised)) (tcp-write! cli (make-bytevector (* 4 1048576) 7) (lambda (s) (void))))))
          (check "P30 tcp: the registration fault reaches the caller" (eq? r 'raised) r)
          (check "P30 tcp: release point hit once, live blocks unchanged" (and (eqv? (hits 'write-block-released-register-fail) 1) (eqv? (write-blocks-live-count) w0)) (list (hits 'write-block-released-register-fail) (write-blocks-live-count) w0)))
        (inject-disarm!)
        (let ((st #f))
          (check "P30 tcp: a following write is accepted" (tcp-write! cli (make-bytevector 16 1) (lambda (s) (set! st s))))
          (check "P30 tcp: ...and completes with status 0" (within? 2000 (lambda () (eqv? st 0))) st))
        (count! 'write-block-released-plain-neg)
        (inject-arm-return! 'uv-write-neg -1 1)
        (let ((st #f))
          (let ((r (tcp-write! cli (make-bytevector (* 4 1048576) 6) (lambda (s) (set! st s)))))
            (check "P30 tcp: negative submission -> #f, on-done negative, release point hit once" (and (not r) (eqv? st -1) (eqv? (hits 'write-block-released-plain-neg) 1)) (list r st (hits 'write-block-released-plain-neg)))))
        (inject-disarm!)
        ;; the in-region rejection with an ALLOCATED block: a writer parks at
        ;; 'write-before-region (after the allocation, before the region), the conn is
        ;; closed meanwhile, and the resumed writer meets the state check inside the
        ;; region: the block is released at the plain-reject site
        (count! 'write-block-released-plain-reject)
        (let* ((t (inject-arm-barrier! 'write-before-region 1 60000))
               (st 'none)
               ;; past the 64 KiB scratch path: a small write never reaches the point (measured)
               (writer (spawn (lambda () (send main (vector 'wrote (tcp-write! cli (make-bytevector 1048576 2) (lambda (s) (set! st s))))))))
               (w (inject-barrier-wait t 'write-before-region 5000)))
          (check "P30 tcp: the writer parked after allocating its block, before the region" (and (pair? w) (eq? (cdr w) writer)) (if (pair? w) (process-id (cdr w)) w))
          (check "P30 tcp: ...holding one live block" (eqv? (write-blocks-live-count) (+ w0 1)) (write-blocks-live-count) w0)
          (tcp-close! cli)
          (when (pair? w) (send (cdr w) (vector 'inject-resume t)) (guard (e (#t (void))) (inject-release! t)))
          (guard (e (#t (void))) (inject-barrier-cleanup! t 'write-before-region 2000))
          (receive (after 3000 (check "P30 tcp: the write returned" #f 'timeout))
            (`#(wrote ,r) (check "P30 tcp: the in-region rejection refused it, on-done -1, the block released at the plain-reject site once" (and (not r) (eqv? st -1) (eqv? (hits 'write-block-released-plain-reject) 1) (eqv? (write-blocks-live-count) w0)) (list r st (hits 'write-block-released-plain-reject) (write-blocks-live-count) w0)))))
        (within? 2000 (lambda () (not (conn? srv))))
        (when srv (tcp-close! srv))
        (tcp-stop-listen! l)
        (inject-disarm!)
        (check "P30 tcp: live blocks and table back" (within? 3000 (lambda () (and (eqv? (write-blocks-live-count) w0) (eqv? (write-table-size) t0)))) (list (write-blocks-live-count) (write-table-size)))
        (back-to-base! "P30 tcp: counts back" b0 5000))

      (check "baseline: all five counts exact" (equal? (base) b0) (base) b0))
    (if (zero? fails)
        (begin (display "ALL PROC-FAULTS TESTS PASSED\n") (exit 0))
        (begin (display "PROC-FAULTS VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))))
