#!chezscheme
;; Child processes -- seam-driven fault cells (proc-spawn design v4-v8 §5).
;;   P15  the exit is delivered exactly once for the returned proc (the region holds;
;;        the mutant-gap red proof lives in a separate driver)
;;   P18  the orphan path: uv_spawn's result overridden to -1 with a real child started;
;;        and a publication fault after the proc row went in
;;   P21  callback allocation faults: exit notification, close-path unindex
;;   P24  the failed-spawn queue repair (F13): (a) the real error: path via a bogus stdio
;;        stream, (b) the simulated queue removal on an active orphan; neighbours around both
;;   P25  the process handle block is retained until the row retires (address log)
;;   P27  rollback faults: pipe init skipped, read-start negative, publish/index/recover faults,
;;        rollback unindex fault, orphan publish fault
;;   P28  shutdown faults: registration raise, negative submission (skipped call)
;;   P29  close-callback containment: unindex fault on a pipe conn
;;   P30  write-block ownership (plaintext): registration fault on the queued path
(import (chezscheme) (igropyr actor) (igropyr tcp)
        (only (igropyr libuv) now-ms uv-live-handle-count)
        (igropyr inject-control))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (within? ms thunk)
  (let ((deadline (+ (now-ms) ms)))
    (let loop () (cond ((thunk) #t) ((> (now-ms) deadline) #f) (else (sleep-ms 20) (loop))))))
(define (spawn-sh cmd . opts) (apply proc-spawn! "/bin/sh" (list "sh" "-c" cmd) opts))
(define (failed? r) (and (pair? r) (eq? (car r) 'failed)))
(define (wait-exit p ms) (receive (after ms 'timeout) (`#(proc-exit ,@p ,code ,signal) (cons code signal))))
(define (cat bvs)
  (let* ((n (apply + (map bytevector-length bvs))) (out (make-bytevector n)))
    (let loop ((bvs bvs) (o 0))
      (unless (null? bvs)
        (bytevector-copy! (car bvs) 0 out o (bytevector-length (car bvs)))
        (loop (cdr bvs) (+ o (bytevector-length (car bvs))))))
    out))
(define (collect p stream ms)
  (let ((deadline (+ (now-ms) ms)))
    (let loop ((acc '()))
      (receive (after (max 1 (- deadline (now-ms))) (cons 'partial (cat (reverse acc))))
        (`#(proc-data ,@p ,@stream ,bv) (loop (cons bv acc)))
        (`#(proc-eof ,@p ,@stream) (cat (reverse acc)))))))
(define (base) (list (uv-live-handle-count) (conn-count) (pipe-conn-count) (proc-count) (uv-owner-index-count)))
(define (back-to-base! label b ms) (check label (within? ms (lambda () (equal? (base) b))) (base) b))
(define (hits point) (or (inject-hits point) 0))
(define (stat key) (let ((a (assq key (proc-stats)))) (and a (cdr a))))
(define (pid-alive? pid) (eqv? 0 (system (string-append "kill -0 " (number->string pid) " 2>/dev/null"))))
(define (drain! ms) (let loop () (receive (after ms (void)) (`#(proc-data ,p ,s ,bv) (loop)) (`#(proc-eof ,p ,s) (loop)) (`#(proc-exit ,p ,c ,g) (loop)) (`#(proc-error ,p ,s ,n) (loop)))))
(define (finish! p) (when (proc? p) (guard (e (#t (void))) (proc-kill! p 9)) (wait-exit p 3000) (proc-close! p) (drain! 300)))
(define port 18810)
;; neighbours for P24: two listeners before, closed after; two more, then closed
(define (with-neighbours thunk)
  (let ((l1 (tcp-listen! "127.0.0.1" port 16 (lambda (c) (void))))
        (l2 (tcp-listen! "127.0.0.1" (+ port 1) 16 (lambda (c) (void)))))
    (thunk)
    (tcp-stop-listen! l1) (tcp-stop-listen! l2)
    (sleep-ms 50)
    (let ((l3 (tcp-listen! "127.0.0.1" (+ port 2) 16 (lambda (c) (void))))
          (l4 (tcp-listen! "127.0.0.1" (+ port 3) 16 (lambda (c) (void)))))
      (sleep-ms 50)
      (tcp-stop-listen! l3) (tcp-stop-listen! l4))))

(start-scheduler
  (lambda ()
    (define main self)
    (register 'main self)
    (let ((b0 (base)))

      ;; ---- P15: exactly one exit for the returned proc ----------------------------------
      (let ((p (spawn-sh "true")))
        (check "P15: the exit is for the returned proc" (equal? (wait-exit p 3000) '(0 . 0)))
        (receive (after 500 (check "P15: exactly one exit" #t)) (`#(proc-exit ,@p ,c ,s) (check "P15: exactly one exit" #f (list c s))))
        (check "P15: the no-row path was never taken" (eqv? (hits 'proc-exit-cb-no-row) 0) (hits 'proc-exit-cb-no-row))
        (drain! 300)
        (back-to-base! "P15: counts back" b0 3000))

      ;; ---- P18: the orphan path ---------------------------------------------------------------
      (let ((h0 (hits 'proc-exit-cb-no-row)))
        (inject-arm-return! 'proc-uv-spawn-result -1 1)
        (let ((r (spawn-sh "exec sleep 100")))
          (check "P18: the caller gets a failure although a child was started" (failed? r) r)
          (check "P18: the orphan was counted while it lived, then reaped: counts back within 2 s" (within? 2000 (lambda () (equal? (base) b0))) (base) b0)
          (check "P18: the orphan's exit went through its row, not the no-row path" (eqv? (hits 'proc-exit-cb-no-row) h0) (hits 'proc-exit-cb-no-row))
          (drain! 300)))
      (let ((r (begin (inject-arm-fault! 'proc-publish-fail 1) (guard (e (#t (cons 'raised e))) (spawn-sh "exec sleep 100")))))
        (check "P18 publish: the condition reaches the caller" (and (pair? r) (eq? (car r) 'raised)) (if (pair? r) (car r) r))
        (back-to-base! "P18 publish: unpublished, orphan killed and reaped, counts back" b0 3000)
        (drain! 300))

      ;; ---- P21: callback allocation faults -------------------------------------------------------
      (let ((p (begin (inject-arm-fault! 'proc-exit-notify 1) (spawn-sh "true"))))
        (check "P21 exit-notify: no exit message (the notification raised inside its guard)" (eq? (wait-exit p 1500) 'timeout))
        (check "P21 exit-notify: the child was still invalidated (pid #f, not running)" (within? 2000 (lambda () (and (not (proc-pid p)) (not (eq? (proc-state p) 'running))))) (list (proc-pid p) (proc-state p)))
        (check "P21 exit-notify: closed" (within? 3000 (lambda () (eq? (proc-state p) 'closed))) (proc-state p))
        (drain! 300)
        (back-to-base! "P21 exit-notify: counts back" b0 3000))

      ;; ---- P24: the F13 repair with neighbours ---------------------------------------------------
      (let ((lk0 (hits 'proc-f13-linked)) (rl0 (hits 'proc-f13-relinked)))
        (with-neighbours
          (lambda ()
            (inject-arm-return! 'proc-stdio-bogus-stream #t 1)
            (let ((r (spawn-sh "true")))
              (check "P24a: a non-pipe stdio stream fails uv_spawn before any fork (EINVAL)" (failed? r) r))))
        (drain! 300)
        (let ((lk (- (hits 'proc-f13-linked) lk0)) (rl (- (hits 'proc-f13-relinked) rl0)))
          (check "P24a: exactly one repair branch ran" (= (+ lk rl) 1) (list lk rl))
          (display "  [P24a] branch: ") (display (if (= rl 1) "relinked (libuv removed the handle on error: 1.52 behaviour)" "linked (1.50 behaviour)")) (newline))
        (back-to-base! "P24a: no crash, handles and counts exact after neighbour churn" b0 3000))
      (let ((rl0 (hits 'proc-f13-relinked)))
        (with-neighbours
          (lambda ()
            (inject-arm-return! 'proc-uv-spawn-result -1 1)
            (inject-arm-return! 'proc-simulate-queue-removal #t 1)
            (let ((r (spawn-sh "exec sleep 100")))
              (check "P24b: active orphan with its queue node removed: failure returned" (failed? r) r))
            (check "P24b: the orphan was killed and reaped" (within? 2000 (lambda () (eqv? (proc-count) (list-ref b0 3)))) (proc-count))))
        (drain! 300)
        (check "P24b: the relinked branch ran once" (eqv? (- (hits 'proc-f13-relinked) rl0) 1) (hits 'proc-f13-relinked))
        (back-to-base! "P24b: no crash, handles and counts exact" b0 3000))

      ;; ---- P25: the handle block is retained until the row retires --------------------------
      (let ((a (spawn-sh "read x; echo x; exit 0")) (f0 (hits 'proc-handle-freed)))
        (proc-read-stop! a 'stdout)
        (proc-write! a (string->utf8 "go\n"))
        (check "P25: A exited" (equal? (wait-exit a 3000) '(0 . 0)))
        (check "P25: A's process handle closed, row still open (stdout read-stopped)" (within? 2000 (lambda () (eq? (proc-state a) 'exited))) (proc-state a))
        (let ((later (let loop ((i 0) (acc '())) (if (= i 100) acc (loop (+ i 1) (cons (spawn-sh "true") acc))))))
          (for-each (lambda (p) (wait-exit p 5000)) later)
          (drain! 500)
          (check "P25: 100 later children finished" (within? 5000 (lambda () (eqv? (proc-count) (+ (list-ref b0 3) 1)))) (proc-count)))
        (check "P25: proc-table[handle A] is still A (identity)" (eq? ($proc-table-ref (proc-handle a)) a))
        (check "P25: A's handle block has not been freed" (eqv? (hits 'proc-handle-freed) (+ f0 100)) (list (hits 'proc-handle-freed) f0))
        (proc-read-start! a 'stdout)
        (check "P25: A's data and EOF after read-start" (equal? (collect a 'stdout 3000) (string->utf8 "x\n")))
        (collect a 'stderr 2000)
        (check "P25: A closed and its block freed exactly once" (within? 3000 (lambda () (and (eq? (proc-state a) 'closed) (eqv? (hits 'proc-handle-freed) (+ f0 101))))) (list (proc-state a) (hits 'proc-handle-freed)))
        (back-to-base! "P25: counts back" b0 3000))

      ;; ---- P27: rollback faults ------------------------------------------------------------
      (inject-arm-return! 'proc-alloc-pipe-fail -1 1)
      (let ((r (spawn-sh "true")))
        (check "P27 pipe-init: failure returned (synthetic pre-initialisation failure)" (failed? r) r)
        (check "P27 pipe-init: nothing published, everything released" (equal? (base) b0) (base) b0))
      (inject-arm-return! 'proc-read-start-result -1 1)
      (let ((r (spawn-sh "exec sleep 100")))
        (check "P27 read-start: failure returned" (failed? r) r)
        (back-to-base! "P27 read-start: active rollback, child killed and reaped, counts back" b0 3000)
        (drain! 300))
      (inject-arm-fault! 'proc-publish-index-fail 1)
      (let ((r (guard (e (#t 'raised)) (spawn-sh "exec sleep 100"))))
        (check "P27 index: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 index: the orphan stayed in proc-count while it lived" (or (eqv? (proc-count) (+ (list-ref b0 3) 1)) (eqv? (proc-count) (list-ref b0 3))) (proc-count))
        (back-to-base! "P27 index: reaped through its row, counts back" b0 3000)
        (drain! 300))
      (inject-arm-fault! 'proc-recover-index-fail 1)
      (inject-arm-fault! 'proc-publish-index-fail 1)
      (let ((u0 (hits 'proc-orphan-unindexed)) (r (guard (e (#t 'raised)) (spawn-sh "exec sleep 100"))))
        (check "P27 recover: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 recover: the row was kept without its owner entry (counted once)" (within? 2000 (lambda () (eqv? (hits 'proc-orphan-unindexed) (+ u0 1)))) (hits 'proc-orphan-unindexed))
        (back-to-base! "P27 recover: reaped, counts back" b0 3000)
        (drain! 300))
      (inject-arm-fault! 'proc-rollback-unindex 1)
      (inject-arm-fault! 'proc-publish-fail 1)
      (let ((r (guard (e (#t 'raised)) (spawn-sh "exec sleep 100"))))
        (check "P27 rollback-unindex: the condition reaches the caller" (eq? r 'raised) r)
        (check "P27 rollback-unindex: the rest of the rollback ran (handles, conns, procs back); exactly one index entry leaked"
               (within? 3000 (lambda () (equal? (list-head (base) 4) (list-head b0 4)))) (base) b0)
        (check "P27 rollback-unindex: the leak is one entry" (eqv? (uv-owner-index-count) (+ (list-ref b0 4) 1)) (uv-owner-index-count) (list-ref b0 4))
        (drain! 300))
      (let ((b1 (base)))
        (inject-arm-fault! 'proc-orphan-publish 1)
        (inject-arm-return! 'proc-uv-spawn-result -1 1)
        (let ((h0 (hits 'proc-exit-cb-no-row)) (r (guard (e (#t 'raised)) (spawn-sh "exec sleep 100"))))
          (check "P27 orphan-publish: the caller sees the failure or the condition" (or (failed? r) (eq? r 'raised)) r)
          (check "P27 orphan-publish: the handle stayed registered and the exit took the no-row path" (within? 3000 (lambda () (eqv? (hits 'proc-exit-cb-no-row) (+ h0 1)))) (hits 'proc-exit-cb-no-row))
          (back-to-base! "P27 orphan-publish: freed by the no-row close path, counts back" b1 3000)
          (drain! 300)))

      ;; ---- P28: shutdown faults ----------------------------------------------------------------
      (let ((p (spawn-sh "exec cat")) (b1 (base)))
        (inject-arm-fault! 'proc-shutdown-register 1)
        (let ((r (guard (e (#t 'raised)) (proc-stdin-close! p))))
          (check "P28 register: the condition reaches the caller" (eq? r 'raised) r)
          (check "P28 register: the pipe was closed, the request freed (pending 0)" (within? 2000 (lambda () (and (not (proc-stdin p)) (eqv? (stat 'shutdown-pending) 0)))) (list (proc-stdin p) (stat 'shutdown-pending)))
          (check "P28 register: cat exits at EOF" (equal? (wait-exit p 3000) '(0 . 0)))
          (drain! 300)
          (back-to-base! "P28 register: counts back" b0 3000)))
      (let ((p (spawn-sh "exec cat")) (e0 (or (stat 'shutdown-immediate-errors) 0)))
        (inject-arm-return! 'proc-uv-shutdown-result -1 1)
        (check "P28 neg: proc-stdin-close! -> #t (the stream is closing either way)" (proc-stdin-close! p))
        (check "P28 neg: counted as an immediate error, request freed" (within? 2000 (lambda () (and (eqv? (stat 'shutdown-immediate-errors) (+ e0 1)) (eqv? (stat 'shutdown-pending) 0)))) (list (stat 'shutdown-immediate-errors) (stat 'shutdown-pending)))
        (check "P28 neg: the pipe closed, cat exits" (equal? (wait-exit p 3000) '(0 . 0)))
        (drain! 300)
        (back-to-base! "P28 neg: counts back" b0 3000))

      ;; ---- P29: close-callback containment ------------------------------------------------------
      (let ((p (spawn-sh "true")) (b1 (base)))
        (inject-arm-fault! 'conn-close-unindex 1)
        (check "P29: exit" (equal? (wait-exit p 3000) '(0 . 0)))
        (drain! 500)
        (check "P29: the handle was freed, the pipe field cleared and the row retired although unindex raised"
               (within? 3000 (lambda () (and (eq? (proc-state p) 'closed) (equal? (list-head (base) 4) (list-head b0 4))))) (list (proc-state p) (base)))
        (check "P29: exactly one index entry leaked, counted" (and (eqv? (uv-owner-index-count) (+ (list-ref b0 4) 1)) (>= (hits 'conn-close-unindex) 1)) (uv-owner-index-count) (hits 'conn-close-unindex)))

      ;; ---- P30: write-block ownership, plaintext queued path ----------------------------------------
      (let ((p (spawn-sh "exec sleep 5")) (w0 (write-blocks-live-count)) (t0 (write-table-size)))
        (inject-arm-fault! 'write-register-oom 1)
        (let ((r (guard (e (#t 'raised)) (proc-write! p (make-bytevector (* 4 1048576) 9)))))
          (check "P30: the registration fault reaches the caller" (eq? r 'raised) r)
          (check "P30: the block was freed (write-blocks-live back) and the table is unchanged" (and (eqv? (write-blocks-live-count) w0) (eqv? (write-table-size) t0)) (list (write-blocks-live-count) w0 (write-table-size) t0))
          (check "P30: queued refunded" (eqv? (proc-queued p) 0) (proc-queued p)))
        (let ((st #f))
          (check "P30: a following write is accepted" (proc-write! p (make-bytevector 16 1) (lambda (s) (set! st s))))
          (check "P30: ...and completes" (within? 2000 (lambda () st)) st))
        (proc-close! p) (proc-kill! p 9) (wait-exit p 3000) (drain! 300)
        (check "P30: live blocks and table back after the close" (within? 2000 (lambda () (and (eqv? (write-blocks-live-count) w0) (eqv? (write-table-size) t0)))) (list (write-blocks-live-count) (write-table-size)))
        (back-to-base! "P30: counts back" b0 3000))

      (check "baseline: counts (P27/P29 leaks excepted: two index entries)" (equal? (list-head (base) 4) (list-head b0 4)) (base) b0))
    (if (zero? fails)
        (begin (display "ALL PROC-FAULTS TESTS PASSED\n") (exit 0))
        (begin (display "PROC-FAULTS VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))))
