#!chezscheme
;; The vendored conformance fixture's READ table, enforced. test/sexpr.sc
;; consumes only its write_reject section, so the 63 read verdicts -- the
;; ones the other implementation regenerates against -- were checked by
;; nothing in this tree. Every row's verdict is asserted here against the
;; entry point the file names (string->sexpr-extended). Rows that are KNOWN
;; to differ from the file, because a ruling moved them and the file has not
;; been re-vendored yet, are listed by name with the reason: the cell passes
;; when the file and the list disagree on exactly those rows, and fails when
;; they disagree anywhere else OR when a listed row no longer differs (the
;; file was re-vendored: strike it from the list).
(import (chezscheme) (igropyr sexpr) (only (igropyr crypto) base64-decode))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define path
  (let find ((c '("test/sexpr-vectors.json" "sexpr-vectors.json" "igropyr/test/sexpr-vectors.json")))
    (cond ((null? c) (error 'sexpr-fixture-read "vendored fixture not found"))
          ((file-exists? (car c)) (car c))
          (else (find (cdr c))))))
;; the file is JSON; the tree's own JSON reader is not imported to keep this
;; cell independent of it, so a small extraction of exactly the fields used
;; here is done on the text: name, accepted, and the input as either input_b64
;; or input_rule {prefix, repeat, count, suffix} (five rows are generated by
;; rule because a 70000-character token is not worth storing)
(define text (call-with-input-file path get-string-all))
(define (find-from s sub i)
  (let ((n (string-length s)) (m (string-length sub)))
    (let loop ((k i)) (cond ((> (+ k m) n) #f) ((string=? (substring s k (+ k m)) sub) k) (else (loop (+ k 1)))))))
(define (json-string-at s i)
  ;; i is the index of the opening quote; JSON escapes other than \" \\ do not
  ;; occur in these three fields (base64 and identifiers)
  (let loop ((k (+ i 1)) (acc '()))
    (let ((c (string-ref s k)))
      (cond ((char=? c #\") (list->string (reverse acc)))
            ((char=? c #\\) (loop (+ k 2) (cons (string-ref s (+ k 1)) acc)))
            (else (loop (+ k 1) (cons c acc)))))))
(define (field-after s key from to)
  (let ((k (find-from s (string-append "\"" key "\"") from)))
    (and k (< k to)
         (let ((q (find-from s "\"" (+ k (string-length key) 3))))
           (and q (< q to) (json-string-at s q))))))
(define (int-after s key from to)
  (let ((k (find-from s (string-append "\"" key "\"") from)))
    (and k (< k to)
         (let loop ((j (+ k (string-length key) 3)) (acc '()))
           (let ((c (string-ref s j)))
             (cond ((char-numeric? c) (loop (+ j 1) (cons c acc)))
                   ((null? acc) (loop (+ j 1) acc))
                   (else (string->number (list->string (reverse acc))))))))))
;; the input, as bytes: from input_b64, or built from input_rule
(define (row-input s from to)
  (let ((b64 (field-after s "input_b64" from to)))
    (if b64
        (base64-decode b64)
        (let ((r (find-from s "\"input_rule\"" from)))
          (and r (< r to)
               (let* ((pre (field-after s "prefix" r to))
                      (rep (field-after s "repeat" r to))
                      (cnt (int-after s "count" r to))
                      (suf (field-after s "suffix" r to)))
                 (string->utf8
                   (string-append pre
                                  (let loop ((n cnt) (acc '())) (if (= n 0) (apply string-append acc) (loop (- n 1) (cons rep acc))))
                                  suf))))))))
(define (bool-after s key from to)
  (let ((k (find-from s (string-append "\"" key "\"") from)))
    (and k (< k to)
         (let ((v (find-from s "true" k)) (f (find-from s "false" k)))
           (cond ((and v (< v to) (or (not f) (< v f))) #t)
                 ((and f (< f to)) #f)
                 (else (error 'sexpr-fixture-read "no boolean" key)))))))
;; the read section: from "read": [ to the next ] at the same depth
(define read-start (find-from text "\"read\": [" 0))
(define read-end
  (let loop ((k (+ read-start 9)) (depth 1))
    (let ((c (string-ref text k)))
      (cond ((char=? c #\[) (loop (+ k 1) (+ depth 1)))
            ((char=? c #\]) (if (= depth 1) k (loop (+ k 1) (- depth 1))))
            (else (loop (+ k 1) depth))))))
;; each row is one {...} object at depth 1 inside the array
(define rows
  (let loop ((k read-start) (acc '()))
    (let ((o (find-from text "{" k)))
      (if (or (not o) (> o read-end)) (reverse acc)
          (let ((c (let l ((j (+ o 1)) (d 1)) (let ((ch (string-ref text j)))
                                                 (cond ((char=? ch #\{) (l (+ j 1) (+ d 1)))
                                                       ((char=? ch #\}) (if (= d 1) j (l (+ j 1) (- d 1))))
                                                       (else (l (+ j 1) d)))))))
            (loop (+ c 1)
                  (cons (list (field-after text "name" o c)
                              (row-input text o c)
                              (bool-after text "accepted" o c))
                        acc)))))))
(check "the read table was found and has its 63 rows" (= (length rows) 63) (length rows))

;; rows whose FILE verdict is known to be stale, by name, with the reason
(define known-moved
  ;; EMPTY, and that is the finished state. Between 2026-09-12's ruling and the
  ;; re-vendoring this list named four rows -- read-plus-int, read-plus-five,
  ;; read-symbol-dot, read-dot-alone -- which the ruling moved from accepted to
  ;; refused while the vendored file still recorded the old verdict. The other
  ;; implementation regenerated the fixture against cd020e9 (its commit 6df6d37,
  ;; golden md5 c40ab42b9cd2ac4b735c9e9e10371bbd), the file now carries the new
  ;; verdicts, and the list emptied. The mechanism is worth keeping: a listed
  ;; row must DIFFER from the file, so the cell goes red when a re-vendoring
  ;; lands and the list has not been struck -- the reminder is the red, not a
  ;; note someone has to remember to act on.
  '())

(define (reads? bv)
  (guard (e (#t (if (and (vector? e) (fx>= (vector-length e) 2) (eq? (vector-ref e 0) 'sexpr-error)) 'REFUSED (vector 'UNEXPECTED e))))
    (string->sexpr-extended (utf8->string bv))
    'ACCEPTED))
(for-each
  (lambda (row)
    (let* ((name (car row)) (input (cadr row)) (file-says (caddr row))
           (got (reads? input))
           (listed (assoc name known-moved)))
      (cond
        ((vector? got) (check (string-append "read row " name ": the reader raised something that is not its own error") #f got))
        (listed
         (check (string-append "read row " name " differs from the file, as listed: " (cdr listed))
                (not (eq? (eq? got 'ACCEPTED) file-says)) got file-says))
        (else
         (check (string-append "read row " name (if file-says " accepted" " refused"))
                (eq? (eq? got 'ACCEPTED) file-says) got file-says)))))
  rows)
;; the list must not name a row the file does not have
(for-each (lambda (m) (check (string-append "known-moved names a real row: " (car m)) (assoc (car m) rows)))
          known-moved)

(if (zero? fails)
    (begin (display "ALL SEXPR-FIXTURE-READ TESTS PASSED\n") (exit 0))
    (begin (display "SEXPR-FIXTURE-READ VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))
