#!chezscheme
;; M21: the link reaper is away (killed; its replacement held before it
;; registers) while an installed link dies. The replacement's INITIAL rescan
;; must reclaim the entry: its watched table is fresh, so only a rescan can
;; know about the dead link. The periodic scan is set to 60 s before the node
;; starts, so nothing but the initial rescan can act inside the window.
(import (chezscheme) (igropyr actor) (igropyr node)
        (only (igropyr libuv) now-ms)
        (igropyr inject-control)
        (only (igropyr tls-core) tls-live-session-count)
        (only (igropyr tcp) tls-live-watcher-count)
        (test tls-raw-client) (test mesh-proof))
(define fails 0)
(define (check label ok . info)
  (if ok (begin (display "  ok  ") (display label) (newline))
      (begin (set! fails (+ fails 1)) (display "FAIL  ") (display label)
             (for-each (lambda (x) (display " ") (write x)) info) (newline))))
(define (within? ms thunk)
  (let ((deadline (+ (now-ms) ms)))
    (let loop () (cond ((thunk) #t) ((> (now-ms) deadline) #f) (else (sleep-ms 20) (loop))))))
(define dir "/tmp/igropyr-tls-mesh-reaper-restart")
(system (string-append "sh igropyr/test/tls-certs.sh " dir " >/dev/null"))
(putenv "SSL_CERT_FILE" (string-append dir "/ca.pem"))
(define (in-dir f) (string-append dir "/" f))
(define port 18630)
(define secret "tls-mesh-reaper-restart-secret-0123456789abcdef")
(define probe-boot-id "feedfacefeedface")
(define (frame-bytes datum)
  (let ((o (open-output-string)))
    (write datum o)
    (let ((body (get-output-string o)))
      (string->utf8 (string-append (number->string (string-length body)) "\n" body)))))
(define (read-frame s ms)
  (let loop ((acc ""))
    (let* ((n (string-length acc))
           (nl (let scan ((k 0)) (cond ((= k n) #f) ((char=? (string-ref acc k) #\newline) k) (else (scan (+ k 1))))))
           (len (and nl (string->number (substring acc 0 nl)))))
      (if (and len (>= n (+ nl 1 len)))
          (read (open-input-string (substring acc (+ nl 1) (+ nl 1 len))))
          (let ((r (raw-tls-recv! s ms))) (if (bytevector? r) (loop (string-append acc (utf8->string r))) r))))))
(define (join! s)
  (let ((d (read-frame s 4000)))
    (and (pair? d) (eq? (car d) 'challenge)
         (let* ((nonce-a (cadr d)) (bootid-a (cadddr d)) (cb (raw-tls-peer-cb-hash s)))
           (raw-tls-send! s (frame-bytes (list 'hello "b" (v5-proof-d secret nonce-a "b" probe-boot-id 1 "a" bootid-a cb)
                                              "feedfeedfeedfeedfeedfeedfeedfeed" 5 probe-boot-id 1)))
           (let ((w (read-frame s 4000))) (and (pair? w) (eq? (car w) 'welcome)))))))

(start-scheduler
  (lambda ()
    (register 'main self)
    (set-link-reaper-scan-ms! 60000)                 ; read by the reaper at (re)start
    (node-start! 'a secret port "127.0.0.1"
                 (list (cons 'tls-cert (in-dir "good.pem")) (cons 'tls-key (in-dir "good.key"))))
    (monitor-node 'b)
    (let ((base (list (tls-live-session-count) (tls-live-watcher-count)))
          (s (raw-tls-open "127.0.0.1" port "localhost" 5000)))
      (check "M21: TLS session with the node" (not (pair? s)) s)
      (unless (pair? s)
        (check "M21: mesh handshake as b" (join! s))
        (receive (after 3000 (check "M21: node-up b" #f 'timeout)) (`#(node-up b) (check "M21: node-up b" #t)))
        (let* ((reaper (whereis 'igropyr-node-link-reaper))
               (link ($node-link-pid 'b))
               ;; the replacement child is the next arrival at this point
               (t-kid (inject-arm-barrier! 'warden-child-before-register 1 30000)))
          (check "M21: premise -- reaper and link known" (and reaper link (process-alive? reaper) (process-alive? link)))
          (kill reaper 'm21-reaper-killed)
          (let ((k (inject-barrier-wait t-kid 'warden-child-before-register 5000)))
            (check "M21: the warden's replacement reaper parked before registering" (pair? k) k)
            (check "M21: premise -- no reaper is registered during the outage" (not (whereis 'igropyr-node-link-reaper)))
            (kill link 'm21-link-killed-during-outage)
            (check "M21: the link is dead" (within? 2000 (lambda () (not (process-alive? link)))))
            (sleep-ms 1200)
            (check "M21: premise -- during the outage the entry stays (dead link pid in the raw table)" (eq? ($node-link-pid 'b) link))
            (let ((t0 (now-ms)))
              (when (pair? k) (send (cdr k) (vector 'inject-resume t-kid)))
              (check "M21: the replacement's initial rescan reclaimed the entry within 2 s" (within? 2000 (lambda () (not ($node-link-pid 'b)))) (- (now-ms) t0))
              (display "  [M21] reclaimed after ms ") (display (- (now-ms) t0)) (newline))
            (receive (after 3000 (check "M21: node-down b" #f 'timeout)) (`#(node-down b) (check "M21: node-down b" #t)))
            (check "M21: a reaper is registered again" (within? 2000 (lambda () (whereis 'igropyr-node-link-reaper)))))
          (guard (e (#t (void))) (inject-barrier-cleanup! t-kid 'warden-child-before-register 31000)))
        (raw-tls-close! s)
        (check "M21: no peers and watchers back to baseline (session count is unreliable after an in-process kill)"
               (within? 8000 (lambda () (and (not (memq 'b (node-peers))) (= (tls-live-watcher-count) (cadr base)))))
               (list (node-peers) (tls-live-watcher-count)) base)))
    (if (zero? fails)
        (begin (display "ALL TLS-MESH-REAPER-RESTART TESTS PASSED\n") (exit 0))
        (begin (display "TLS-MESH-REAPER-RESTART VERDICT: ") (display fails) (display " failed case(s)\n") (exit 1)))))
