;;; manual-names.ss -- every igropyr-shaped name the manual prints must exist
;;;
;;; Run:  scheme --script tools/manual-names.ss [manual.md] [library-dir]
;;; Defaults: docs/manual.md and ../01-igropyr (a checkout of the master
;;; branch, which is where the sources live -- the manual is on its own
;;; branch and cannot reach them any other way).
;;;
;;; WHAT THIS CATCHES, and it is one specific failure, not a style rule:
;;; a manual section that documents an API which is not there at all --
;;; names that were renamed, or that were never written, or that a writer
;;; invented because they were the obvious name for the thing being
;;; described. Two of those have happened here: a connection-pool section
;;; naming five procedures that no longer existed, and a peek example
;;; calling a predicate that had never existed. Both read perfectly well.
;;; Nothing else in the tree can notice them: the sources compile, the
;;; suite passes, and the manual is prose.
;;;
;;; WHAT IT DOES NOT CATCH, so that nobody reads a pass as more than it is:
;;;   - a name that exists but is documented with the wrong arity, the
;;;     wrong argument order, or the wrong meaning;
;;;   - a name the manual mentions without any code marking around it;
;;;   - anything about examples that are wrong while naming real things.
;;; It answers exactly one question: does this name exist in this library.
;;;
;;; HOW IT DECIDES WHAT TO LOOK AT. A hyphenated token is treated as a
;;; claim about this library when its first segment is also the first
;;; segment of some exported name (`conversation-`, `connpool-`, ...).
;;; Without that filter ordinary hyphenated English drowns the signal.
;;; In prose every backticked token counts, because that is where the
;;; connection-pool section went stale; inside a fenced block only the
;;; head of a form counts, because the other identifiers there belong to
;;; the example, not to us.
;;;
;;; A hit is not automatically a defect: an example may legitimately name
;;; a procedure from another library, or a signature heading may name its
;;; own parameter. Those go in ACCEPTED below, each with the reason it is
;;; not a defect -- an entry with no reason is not an entry.

(import (chezscheme))

;; Keyed by file, because an entry is a statement about one passage. The
;; agent guide deliberately PRINTS a name that does not exist, as its
;; example of an invented one; accepting that globally would switch off
;; the check for the same name in the manual, where it would be the
;; defect itself.
(define ACCEPTED
  '(("manual.md"
     ("monitor-reference" . "parameter name in the (demonitor ...) signature heading")
     ("load-routes!"      . "the example's own application code, marked as such")
     ("parse-auth-header" . "the example's own application code")
     ("start-time"        . "prose naming a quantity in the stuck-worker formula")
     ("bytevector-append" . "Chez builtin used by an example")
     ("with-input-from-file" . "R6RS builtin used by the record-reader example")
     ("make-pcb"          . "prose about the make- naming convention; the record constructor is generated by define-record-type and appears nowhere as text")
     ("ws-connect!"       . "Goeteia's (web ws), shown as the browser side")
     ("ws-send!"          . "Goeteia's (web ws), shown as the browser side")
     ("sse-connect!"      . "Goeteia's (web sse), shown as the browser side"))
    ("igropyr-dev.md"
     ("conversation-parked?" . "printed on purpose as the example of an invented name; the passage is about the fact that it does not exist")
     ("-extended" . "the sexpr row names the string->sexpr-extended variants by their suffix; the full names exist")
     ("node-cron" . "the porting map's LEFT column: the Node package being ported FROM, not a claim about this library")
     ("app-get/" . "a truncated elision (app-get/...) in the Router row; the trailing dots are cell prose"))
    ;; The Chinese manual is a translation of manual.md and inherits its
    ;; accepted names for the same reasons. Keyed separately because the
    ;; suffix match is exact -- "manual.md" is NOT a suffix of
    ;; "manual.zh-cn.md", so nothing is inherited by accident, and a name
    ;; accepted for one file still has to be argued for the other.
    ("manual.zh-cn.md"
     ("monitor-reference"  . "parameter name in the (demonitor ...) signature heading")
     ("load-routes!"       . "the example's own application code, marked as such")
     ("parse-auth-header"  . "the example's own application code")
     ("start-time"         . "prose naming a quantity in the stuck-worker formula")
     ("bytevector-append"  . "Chez builtin used by an example")
     ("make-pcb"           . "prose about the make- naming convention; the record constructor is generated by define-record-type and appears nowhere as text")
     ("ws-connect!"        . "Goeteia's (web ws), shown as the browser side")
     ("ws-send!"           . "Goeteia's (web ws), shown as the browser side")
     ("sse-connect!"       . "Goeteia's (web sse), shown as the browser side"))))

(define (accepted? file tok)
  (let loop ((rest ACCEPTED))
    (cond ((null? rest) #f)
          ((string-suffix? (caar rest) file) (and (assoc tok (cdar rest)) #t))
          (else (loop (cdr rest))))))

;; ---- the library's own names -------------------------------------------

(define (library-form? x) (and (pair? x) (eq? (car x) 'library)))

(define (export-clause x)
  (let loop ((rest (cddr x)))
    (cond ((null? rest) '())
          ((and (pair? (car rest)) (eq? (caar rest) 'export)) (cdar rest))
          (else (loop (cdr rest))))))

(define (flatten-export e)
  (cond ((symbol? e) (list e))
        ((and (pair? e) (eq? (car e) 'rename))
         (map (lambda (p) (if (pair? p) (cadr p) p)) (cdr e)))
        ((pair? e) (apply append (map flatten-export e)))
        (else '())))

(define (exports-of file)
  (guard (c (#t '()))
    (call-with-input-file file
      (lambda (p)
        (let loop ((acc '()))
          (let ((x (read p)))
            (cond ((eof-object? x) acc)
                  ((library-form? x)
                   (loop (append (flatten-export (export-clause x)) acc)))
                  (else (loop acc)))))))))

;; ---- tokens -------------------------------------------------------------

(define (token-char? c)
  (or (char-alphabetic? c) (char-numeric? c)
      (memv c '(#\- #\! #\? #\* #\/ #\< #\> #\= #\+ #\_))))

(define (tokens-in str)
  (let loop ((i 0) (start #f) (out '()))
    (cond
      ((>= i (string-length str))
       (reverse (if start (cons (substring str start i) out) out)))
      ((token-char? (string-ref str i)) (loop (+ i 1) (or start i) out))
      (else (loop (+ i 1) #f (if start (cons (substring str start i) out) out))))))

;; Inside a fenced block only the head of a form is a claim about this
;; library; a bare identifier there is usually the example's own variable.
(define (call-position-tokens str)
  (let loop ((i 0) (out '()))
    (cond
      ((>= i (string-length str)) (reverse out))
      ((char=? (string-ref str i) #\()
       (let scan ((j (+ i 1)))
         (cond ((and (< j (string-length str)) (token-char? (string-ref str j)))
                (scan (+ j 1)))
               ((> j (+ i 1)) (loop j (cons (substring str (+ i 1) j) out)))
               (else (loop (+ i 1) out)))))
      (else (loop (+ i 1) out)))))

(define (backtick-spans str)
  (let loop ((i 0) (out '()))
    (cond
      ((>= i (string-length str)) (reverse out))
      ((char=? (string-ref str i) #\`)
       (let scan ((j (+ i 1)))
         (cond ((>= j (string-length str)) (reverse out))
               ((char=? (string-ref str j) #\`)
                (loop (+ j 1) (cons (substring str (+ i 1) j) out)))
               (else (scan (+ j 1))))))
      (else (loop (+ i 1) out)))))

;; A table row is names in the open: the module map and the contract
;; tables print exported identifiers as bare cell text, with no backticks
;; around them. Those tables are where names are densest and where an
;; invented one reads most plausibly -- and for a while this tool never
;; looked at them: it reported "1 hit" on a document whose whole point is
;; a table of exports, and its pass line read like a clean sweep. A guard
;; whose coverage silently excludes the richest input is worse than no
;; guard, because the green is indistinguishable from not having looked.
(define (table-line? line)
  (let skip ((k 0))
    (cond ((>= k (string-length line)) #f)
          ((char=? (string-ref line k) #\space) (skip (+ k 1)))
          (else (char=? (string-ref line k) #\|)))))

(define (fence-line? line)
  (let skip ((k 0))
    ;; a closing fence is exactly three characters long, so this is > and
    ;; not >=: with >= every closing fence went unrecognised and the
    ;; in-block flag stayed inverted for the rest of the file
    (cond ((> (+ k 3) (string-length line)) #f)
          ((char=? (string-ref line k) #\space) (skip (+ k 1)))
          (else (string=? (substring line k (+ k 3)) "```")))))

;; A slash compound may be one real name (conversation-peek/timeout) or a
;; documentation ELISION packing several names into one cell
;; (app-get/post/put/delete, conversation-gone?/-stale?/...). Only after
;; the whole token misses is it read as an elision: every segment must
;; then resolve to a name that exists -- a plain tail (post) or a "-tail"
;; (-stale?) given the first segment's prefix, or a full name on its own.
;; One unresolvable segment fails the whole token, so an invented name
;; cannot hide inside a list of real ones.
;;
;; THE PLAIN TAIL IS THE ONE THAT LOOKS HARMLESS. Accepting any segment
;; without a hyphen on sight -- which is what this did first -- left the
;; commonest shape in these tables wide open: app-get/post/put/flourish
;; passed, and that is precisely where an invented name would sit. A
;; segment is an abbreviation of something, so it has to name something.
(define (elision-resolves? tok name-set)
  (let ((segs (let loop ((i 0) (start 0) (out '()))
                (cond ((>= i (string-length tok))
                       (reverse (cons (substring tok start i) out)))
                      ((char=? (string-ref tok i) #\/)
                       (loop (+ i 1) (+ i 1)
                             (cons (substring tok start i) out)))
                      (else (loop (+ i 1) start out))))))
    (and (> (length segs) 1)
         (let ((prefix (head-segment (car segs))))
           (for-all
             (lambda (seg)
               (or (string=? seg "")
                   ;; A PLAIN TAIL IS STILL A CLAIM. `post` in
                   ;; app-get/post/... abbreviates app-post, so it is
                   ;; resolved the same way a "-tail" is and has to name
                   ;; something. Accepting any hyphen-free segment on
                   ;; sight was the hole this comment already claimed was
                   ;; closed: app-get/post/put/flourish passed, which is
                   ;; the commonest shape in these tables and exactly
                   ;; where an invented name would sit.
                   (hashtable-ref name-set
                                  (string-append prefix "-" seg) #f)
                   (hashtable-ref name-set seg #f)
                   (and (char=? (string-ref seg 0) #\-)
                        (hashtable-ref name-set
                                       (string-append prefix seg) #f))))
             segs)))))

(define (head-segment s)
  (let loop ((i 0))
    (cond ((>= i (string-length s)) s)
          ((char=? (string-ref s i) #\-) (substring s 0 i))
          (else (loop (+ i 1))))))

(define (string-suffix? suf s)
  (let ((n (string-length s)) (m (string-length suf)))
    (and (>= n m) (string=? (substring s (- n m) n) suf))))

;; ---- the check ----------------------------------------------------------

(define (run manual libdir)
  (unless (file-exists? manual)
    (printf "manual-names: no manual at ~a\n" manual)
    (exit 1))
  (unless (file-directory? libdir)
    ;; Not a pass. Say what is missing and how to supply it, so that a
    ;; skip cannot be mistaken for a clean run.
    (printf "manual-names: SKIPPED -- no library sources at ~a.\n" libdir)
    (printf "  This check needs a checkout of the master branch (the manual\n")
    (printf "  lives on its own branch and the sources are not beside it).\n")
    (printf "  Pass one:  scheme --script tools/manual-names.ss ~a <dir>\n" manual)
    (exit 2))
  (let* ((files (map (lambda (f) (string-append libdir "/" f))
                     (filter (lambda (f) (string-suffix? ".sc" f))
                             (directory-list libdir))))
         (names (map symbol->string (apply append (map exports-of files))))
         (name-set (let ((h (make-hashtable string-hash string=?)))
                     (for-each (lambda (n) (hashtable-set! h n #t)) names)
                     ;; A name that is defined but not exported still exists;
                     ;; this check is about absence, not about visibility.
                     (for-each
                       (lambda (f)
                         (call-with-input-file f
                           (lambda (p)
                             (let loop ()
                               (let ((line (get-line p)))
                                 (unless (eof-object? line)
                                   (for-each (lambda (t) (hashtable-set! h t #t))
                                             (tokens-in line))
                                   (loop)))))))
                       files)
                     h))
         (head-set (let ((h (make-hashtable string-hash string=?)))
                     (for-each (lambda (n) (hashtable-set! h (head-segment n) #t))
                               names)
                     h))
         (hits '())
         ;; how many tokens LOOKED like claims about this library --
         ;; printed beside the hit count, so "0 hits from 4 candidates"
         ;; and "0 hits from 400" stop reading identically
         (candidates 0))
    (when (null? files)
      (printf "manual-names: SKIPPED -- ~a holds no .sc sources\n" libdir)
      (exit 2))
    (call-with-input-file manual
      (lambda (p)
        (let loop ((lineno 1) (in-block #f))
          (let ((line (get-line p)))
            (unless (eof-object? line)
              (cond
                ((fence-line? line) (loop (+ lineno 1) (not in-block)))
                (else
                  (for-each
                    (lambda (span)
                      (for-each
                        (lambda (tok)
                          (when (and (> (string-length tok) 2)
                                     (memv #\- (string->list tok))
                                     ;; "conversation-..." in prose is an
                                     ;; elision, not a name
                                     (not (char=? #\- (string-ref
                                            tok (- (string-length tok) 1))))
                                     (hashtable-ref head-set (head-segment tok) #f))
                            (set! candidates (+ candidates 1))
                            (unless (or (hashtable-ref name-set tok #f)
                                        (elision-resolves? tok name-set))
                              (set! hits (cons (cons tok lineno) hits)))))
                        (if in-block
                            (call-position-tokens span)
                            (tokens-in span))))
                    (cond (in-block (list line))
                          ;; a table row is scanned WHOLE: its cells hold
                          ;; bare names, and tokens-in also picks up any
                          ;; backticked ones, so the row replaces the
                          ;; span scan rather than adding to it
                          ((table-line? line) (list line))
                          (else (backtick-spans line))))
                  (loop (+ lineno 1) in-block))))))))
    (let* ((hits (reverse hits))
           (unexplained
             (filter (lambda (h) (not (accepted? manual (car h)))) hits)))
      (printf "manual-names: ~a name prefixes, ~a candidates examined, ~a hit~a, ~a accepted\n"
              (hashtable-size head-set) candidates (length hits)
              (if (= 1 (length hits)) "" "s")
              (- (length hits) (length unexplained)))
      (cond
        ((null? unexplained)
         (printf "manual-names: ok -- no igropyr-shaped name is missing\n")
         (exit 0))
        (else
          (for-each
            (lambda (h)
              (printf "  ~a:~a: ~a is not in the library\n"
                      manual (cdr h) (car h)))
            unexplained)
          (printf "manual-names: ~a name~a the manual prints do~a not exist.\n"
                  (length unexplained)
                  (if (= 1 (length unexplained)) "" "s")
                  (if (= 1 (length unexplained)) "es" ""))
          (printf "  Fix the manual, or add the name to ACCEPTED with the\n")
          (printf "  reason it is not a defect.\n")
          (exit 1))))))

(let ((a (command-line-arguments)))
  (run (if (>= (length a) 1) (car a) "docs/manual.md")
       (if (>= (length a) 2) (cadr a) "../01-igropyr")))
